### PR TITLE
Protocol version upper bound correction

### LINKED ISSUE #5064: Bug in CDDLs, wrong major_protocol_version
Mary's CDDL defines:

```
mary.major_protocol_version = 1 .. 3
```

However https://github.com/cardano-foundation/CIPs/blob/master/CIP-0059/feature-table.md shows that Mary's major prot ver is 4. And indeed `genCoherentBlock` generates mary blocks wity prot ver 4. I believe the CDDL should read:

```
mary.major_protocol_version = 1 .. 4
```

Similarly, I think we need:
```diff
-shelley.major_protocol_version = 1 .. 3
+shelley.major_protocol_version = 1 .. 2
-alonzo.major_protocol_version = 1 .. 7
+alonzo.major_protocol_version = 1 .. 6
-babbage.major_protocol_version = 1 .. 9
+babbage.major_protocol_version = 1 .. 8
```

Perhaps even the lower bound could be changed for each era too.

However that page also mentions 10 as the Conway max prot ver, but the generators seem to generate a block in Conway with prot ver 11?

### PR DESCRIPTION
**Pull request by Soupstraw**
# Description

close #5064

# Checklist

- [ ] Commits in meaningful sequence and with useful messages.
- [ ] Tests added or updated when needed.
- [ ] `CHANGELOG.md` files updated for packages with externally visible changes.  
      **NOTE: _New section is never added with the code changes._** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#changelogmd)).
- [ ] Versions updated in `.cabal` and `CHANGELOG.md` files when necessary, according to the
      [versioning process](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process).
- [ ] Version bounds in `.cabal` files updated when necessary.  
      **NOTE: _If bounds change in a cabal file, that package itself must have a version increase._** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process)).
- [x] Code formatted (use `scripts/fourmolize.sh`).
- [x] Cabal files formatted (use `scripts/cabal-format.sh`).
- [x] CDDL files are up to date (use `scripts/gen-cddl.sh`)
- [x] [`hie.yaml`](https://github.com/intersectmbo/cardano-ledger/blob/master/hie.yaml) updated (use `scripts/gen-hie.sh`).
- [ ] Self-reviewed the diff.

### CODE REVIEW

**Comment by jasagredo** [comment]
This looks reasonable, but I wonder why don't we also change the lower bound? I would expect that to be `eraProtVerLow`.

File: eras/allegra/impl/testlib/Test/Cardano/Ledger/Allegra/CDDL.hs [hunk 1]
```diff
@@ -1,17 +1,22 @@
...
-{-# LANGUAGE NoImplicitPrelude #-}
-{-# OPTIONS_GHC -Wno-unrecognised-pragmas #-}
-
 {-# HLINT ignore "Use camelCase" #-}
 {-# HLINT ignore "Evaluate" #-}
+{-# LANGUAGE RankNTypes #-}
+{-# LANGUAGE ScopedTypeVariables #-}
+{-# LANGUAGE TypeApplications #-}
+{-# LANGUAGE NoImplicitPrelude #-}
+{-# OPTIONS_GHC -Wno-unrecognised-pragmas #-}
```
Comment (jasagredo) [inline eras/allegra/impl/testlib/Test/Cardano/Ledger/Allegra/CDDL.hs]: I would suggest removing this option. In case you need to use it for HLINT you an just use
```
{- HLINT blah -}
```
instead of making it a pragma. Same with Fourmolu

File: eras/shelley/impl/testlib/Test/Cardano/Ledger/Shelley/CDDL.hs [hunk 2]
```diff
@@ -83,13 +89,13 @@ operational_cert =
 next_major_protocol_version :: Integer
 next_major_protocol_version = 3
 
-major_protocol_version :: Rule
-major_protocol_version = "major_protocol_version" =:= (1 :: Integer) ... next_major_protocol_version
+major_protocol_version :: forall era. Era era => Rule
+major_protocol_version = "major_protocol_version" =:= (1 :: Integer) ... getVersion @Integer (eraProtVerHigh @era)
```
Comment (lehins) [inline eras/shelley/impl/testlib/Test/Cardano/Ledger/Shelley/CDDL.hs]: Byron actually started at `0`. To make it clear we could actually use the `eraProtVerLow` of Byron era. Also for each era we allow a major protocol version that the next era will start in, otherwise we would not be able to upgrade current era to the next one.
```suggestion
major_protocol_version = "major_protocol_version" =:= (getVersion @Integer (eraProtVerLOw @ByronEra) ... succ (getVersion @Integer (eraProtVerHigh @era))
```

File: eras/shelley/impl/testlib/Test/Cardano/Ledger/Shelley/CDDL.hs [hunk 3]
```diff
@@ -83,13 +89,13 @@ operational_cert =
 next_major_protocol_version :: Integer
```
Comment (lehins) [inline eras/shelley/impl/testlib/Test/Cardano/Ledger/Shelley/CDDL.hs]: Looks like this definition can now be removed

File: eras/alonzo/impl/cddl-files/alonzo.cddl [hunk 4]
```diff
@@ -55,7 +55,7 @@ signature = bytes .size 64
 
 protocol_version = (major_protocol_version, uint)
 
-major_protocol_version = 1 .. 7
+major_protocol_version = 1 .. 6
```
Comment (lehins) [inline eras/alonzo/impl/cddl-files/alonzo.cddl]: You see, this one was actually correct.

**Review by lehins — APPROVED** [review]
It's crazy how inconsistent protocol version specification was for many eras :see_no_evil: 

Thank you for fixing it.

File: eras/shelley/impl/testlib/Test/Cardano/Ledger/Shelley/CDDL.hs [hunk 5]
```diff
@@ -75,21 +80,15 @@ operational_cert =
...
--- https://github.com/input-output-hk/cuddle/issues/29 is addressed in cuddle.
---
--- next_major_protocol_version :: Rule
--- next_major_protocol_version = "next_major_protocol_version" =:= (10 :: Integer)
-next_major_protocol_version :: Integer
-next_major_protocol_version = 3
+major_protocol_version :: forall era. Era era => Rule
+major_protocol_version =
+  "major_protocol_version"
+    =:= (getVersion @Integer (eraProtVerLow @ByronEra) ... succ (getVersion @Integer (eraProtVerHigh @era)))
```
Comment (jasagredo) [inline eras/shelley/impl/testlib/Test/Cardano/Ledger/Shelley/CDDL.hs:86]: Is it the case that on any era the protocol version provided can be the one of any of the previous eras too? Why isn't this:

```suggestion
    =:= (getVersion @Integer (eraProtVerLow @era) ... succ (getVersion @Integer (eraProtVerHigh @era)))
```
?

**Review by jasagredo — CHANGES_REQUESTED** [review]

File: eras/shelley/impl/testlib/Test/Cardano/Ledger/Shelley/CDDL.hs (hunk 5 above)
Comment (Soupstraw) [reply eras/shelley/impl/testlib/Test/Cardano/Ledger/Shelley/CDDL.hs:86]: I don't know the history behind this, maybe @lehins knows something?

Comment (lehins) [reply eras/shelley/impl/testlib/Test/Cardano/Ledger/Shelley/CDDL.hs:86]: @jasagredo This has nothing to do with history. CDDL is the specification of what values are allowed by the decoders in any particular era. So, this CDDL value for `major_protocol_version` is not the protocol version range that era uses, but is the protocol version range that would be allowed in the transaction in that era, which is the very first byron version `0` to current highest protocol version for the era plus one (hence the `succ`), in order to be able to upgrade to the next era.

Comment (lehins) [reply eras/shelley/impl/testlib/Test/Cardano/Ledger/Shelley/CDDL.hs:86]: FTR. You would **not** be able to submit a transaction that proposes to upgrade to an incompatible protocol version (eg. major protocol version `1` in Babbage), but such transaction will be rejected due to Ledger rules, not the decoders.  CDDL spec is only concerned with serializaton, not the rules.

**Review by jasagredo — APPROVED** [review]
