### PR TITLE
Fail `PlutusV1-V3` translation for direct deposits and balance intervals

### LINKED ISSUE #5634: Fail Plutus translation with DirectDeposit and BalanceInterval
Ensure translation of context for PlutusV1-V3 fails for:
* [ ] - `directDepositsTxBodyL`
* [ ] - and `accountBalanceIntervalsTxBodyL`

This ticket tracks the actual translation and imp spec tests for all of those cases

These two types of failure cases should be done either in two separate PRs, or at the very least two separate commits.

### PR DESCRIPTION
**Pull request by Lucsanszky**
# Description
Resolves #5634 

# Checklist

- [ ] Commits in meaningful sequence and with useful messages.
- [ ] Tests added or updated when needed.
- [ ] `CHANGELOG.md` files updated for packages with externally visible changes.  
      **NOTE: _New section is never added with the code changes._** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#changelogmd)).
- [ ] Versions updated in `.cabal` and `CHANGELOG.md` files when necessary, according to the
      [versioning process](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process).
- [ ] Version bounds in `.cabal` files updated when necessary.  
      **NOTE: _If bounds change in a cabal file, that package itself must have a version increase._** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process)).
- [x] Code formatted (use `scripts/fourmolize.sh`).
- [x] Cabal files formatted (use `scripts/cabal-format.sh`).
- [x] CDDL files are up to date (use `scripts/gen-cddl.sh`)
- [x] [`hie.yaml`](https://github.com/intersectmbo/cardano-ledger/blob/master/hie.yaml) updated (use `scripts/gen-hie.sh`).
- [ ] Self-reviewed the diff.

### CODE REVIEW

File: eras/dijkstra/impl/src/Cardano/Ledger/Dijkstra/TxInfo.hs [hunk 1]
```diff
@@ -94,7 +95,9 @@ data DijkstraContextError era
     SubTxContextError TxId (ContextError era)
   | PointerPresentInOutput (NonEmpty (TxOut era))
   | -- | Attempt to use PlutusV1-V3 in a sub-transaction will result in this failure
-    SubTxIsNotSupported TxId
+    SubTxIsNotSupported !TxId
+  | -- | Attempt to use PlutusV1-V3 with non-empty direct deposits will result in this failure
+    DirectDepositsNotSupported !DirectDeposits
```
Comment (lehins) [inline eras/dijkstra/impl/src/Cardano/Ledger/Dijkstra/TxInfo.hs]: Since recent PR #5672 all `ContextError`s are switched to being lazy

File: eras/dijkstra/impl/testlib/Test/Cardano/Ledger/Dijkstra/TxInfoSpec.hs [hunk 2]
```diff
@@ -120,3 +121,23 @@ spec = describe "TxInfo" $ do
               <$> unPlutusTxInfoResult (toPlutusTxInfo slang ledgerTxInfo)
         pure $
           txInfoResult `shouldBeLeft` inject (DirectDepositsNotSupported @era dd)
+      prop "AccountBalanceIntervalsNotSupported" $ do
+        abi <- arbitrary `suchThat` (not . null . unAccountBalanceIntervals)
```
Comment (lehins) [inline eras/dijkstra/impl/testlib/Test/Cardano/Ledger/Dijkstra/TxInfoSpec.hs]: It usually better to avoid `suchThat`, because it relies on `discards`, which not only result in less efficient tests, but also can sometimes lead to flaky tests due to `Too many discards`. Naturally latter is not a danger here, but it is best to avoid this strategy all together. 
Here is a more clever approach, which relies on `Arbitrary` for `NonEmptyMap` instead: https://github.com/IntersectMBO/cardano-ledger/blob/9ae77d611ad86ae58add04b6042ab730272f2327/libs/cardano-data/testlib/Test/Cardano/Data/Arbitrary.hs#L39
```suggestion
      prop "AccountBalanceIntervalsNotSupported" $ \neAccountBalanceIntervals -> do
        let accountBalanceIntervals =
               AccountBalanceIntervals $ NEM.toMap neAccountBalanceIntervals

**Review by lehins — COMMENTED** [review]
Looks good. I've reviewed individual commits, since it now needs a rebase on `master`, cause #5636 has been finally merged.

**Review by lehins — APPROVED** [review]
Perfect! Thank you!
