### PR TITLE
Fix `metadatum` decoder and `chain_code` CDDL

### LINKED ISSUE #5639: Move validation of Metadata sizes into the decoder
With recent discovery thanks to AntiGen of invalid CDDL spec about the Metadata sizes, turned out to that checking is done in the rules, instead of the decoder, which was revealed by this comment:

https://github.com/IntersectMBO/cardano-ledger/blob/cb57dc730a03ca8af963880c89c8edd301a6d9a9/libs/cardano-ledger-core/src/Cardano/Ledger/Metadata.hs#L134-L135

Instead of relaxing the CDDL, as it was done in #5597 we need perform this check the decoder instead of the Ledger rules. 

Remove this validation:

https://github.com/IntersectMBO/cardano-ledger/blob/cb57dc730a03ca8af963880c89c8edd301a6d9a9/libs/cardano-ledger-core/src/Cardano/Ledger/Metadata.hs#L75-L87

And make sure decoders verify the length

### PR DESCRIPTION
**Pull request by Soupstraw**
# Description

This PR fixes the CDDL and makes changes to some decoders to ensure that the spec and decoders match up. 

 * Removed `.size` control from `chain_code` so the CDDL matches the decoder
 * Updated `Metadatum` decoder so that the failure happens during decoding, not in the rules. I also removed the metadatum check from rules.

close https://github.com/IntersectMBO/cardano-ledger/issues/5639

# Checklist

- [ ] Commits in meaningful sequence and with useful messages.
- [ ] Tests added or updated when needed.
- [ ] `CHANGELOG.md` files updated for packages with externally visible changes.  
      **NOTE: _New section is never added with the code changes._** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#changelogmd)).
- [ ] Versions updated in `.cabal` and `CHANGELOG.md` files when necessary, according to the
      [versioning process](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process).
- [ ] Version bounds in `.cabal` files updated when necessary.  
      **NOTE: _If bounds change in a cabal file, that package itself must have a version increase._** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process)).
- [x] Code formatted (use `scripts/fourmolize.sh`).
- [x] Cabal files formatted (use `scripts/cabal-format.sh`).
- [x] CDDL files are up to date (use `scripts/gen-cddl.sh`)
- [x] [`hie.yaml`](https://github.com/intersectmbo/cardano-ledger/blob/master/hie.yaml) updated (use `scripts/gen-hie.sh`).
- [ ] Self-reviewed the diff.

### CODE REVIEW

File: libs/cardano-ledger-core/src/Cardano/Ledger/Metadata.hs [hunk 1]
```diff
@@ -107,21 +95,15 @@ encodeMetadatum (Map kvs) =
...
--- on the chain. We accept both definte and indefinite representations.
+-- on the chain. We accept both definite and indefinite representations.
 --
--- The byte and string length checks are not enforced in this decoder, but
+-- The byte and string length checks are enforced in this decoder as per
+-- the CDDL spec.
 decodeMetadatum :: Decoder s Metadatum
 decodeMetadatum = do
+  dv <- getDecoderVersion
+  let checkSizes = dv > natVersion @2
```
Comment (lehins) [inline libs/cardano-ledger-core/src/Cardano/Ledger/Metadata.hs:109]: We need to also fix CDDL for Shelly to not include this check and maybe add a comment to this decoder saying that starting with Allegra era we enforce the length to be no more than 64 bytes

File: eras/shelley/impl/src/Cardano/Ledger/Shelley/SoftForks.hs [hunk 2]
```diff
@@ -3,17 +3,11 @@
 {-# LANGUAGE TypeApplications #-}
 
 module Cardano.Ledger.Shelley.SoftForks (
-  validMetadata,
   restrictPoolMetadataHash,
 ) where
 
 import Cardano.Ledger.BaseTypes (ProtVer (..), natVersion)
 
-validMetadata ::
```
Comment (lehins) [inline eras/shelley/impl/src/Cardano/Ledger/Shelley/SoftForks.hs:12]: Such removal need to be mentioned in the changelog

File: libs/cardano-ledger-core/src/Cardano/Ledger/Metadata.hs [hunk 3]
```diff
@@ -69,22 +73,6 @@ instance EncCBOR Metadatum where
 instance DecCBOR Metadatum where
   decCBOR = decodeMetadatum
 
--- Validation of sizes
-
-validMetadatum :: Metadatum -> Bool
```
Comment (lehins) [inline libs/cardano-ledger-core/src/Cardano/Ledger/Metadata.hs:74]: This removal need to be mentioned in the changelog as well

File: eras/shelley/impl/testlib/Test/Cardano/Ledger/Shelley/Arbitrary.hs [hunk 4]
```diff
@@ -536,17 +536,17 @@ sizedMetadatum :: Int -> Gen Metadatum
...
     ]
 sizedMetadatum n =
   let xsGen = listOf (sizedMetadatum (n - 1))
    in oneof
         [ Map <$> (zip <$> resize maxMetadatumListLens xsGen <*> xsGen)
         , List <$> resize maxMetadatumListLens xsGen
         , I <$> arbitrary
-        , B <$> arbitrary
-        , S . T.pack <$> arbitrary
+        , genDatumBytestring
```
Comment (lehins) [inline eras/shelley/impl/testlib/Test/Cardano/Ledger/Shelley/Arbitrary.hs]: Could you please rename this function to reflect the reality a bit better and make the naming more consistent with other generators in the module (will need a changelog entry)
```suggestion
        , genMetadatumByteArray
```

File: eras/shelley/impl/testlib/Test/Cardano/Ledger/Shelley/Arbitrary.hs [hunk 5]
```diff
@@ -536,17 +536,17 @@ sizedMetadatum :: Int -> Gen Metadatum
...
+        , genDatumString
```
Comment (lehins) [inline eras/shelley/impl/testlib/Test/Cardano/Ledger/Shelley/Arbitrary.hs]: Ditto. (too, will need a changelog entry)
```suggestion
        , genMetdatumText
```

File: eras/shelley/impl/testlib/Test/Cardano/Ledger/Shelley/Binary/RoundTrip.hs [hunk 6]
```diff
@@ -9,13 +9,19 @@
 module Test.Cardano.Ledger.Shelley.Binary.RoundTrip (
   roundTripShelleyCommonSpec,
   roundTripStateEraTypesSpec,
+  metadatumSizeLimitSpec,
```
Comment (lehins) [inline eras/shelley/impl/testlib/Test/Cardano/Ledger/Shelley/Binary/RoundTrip.hs]: This doesn't really need to be exported
```suggestion
```

File: eras/shelley/impl/testlib/Test/Cardano/Ledger/Shelley/Binary/RoundTrip.hs [hunk 7]
```diff
@@ -60,6 +68,34 @@ roundTripStateEraTypesSpec = do
...
     roundTripEraTypeSpec @era @NewEpochState
 
+metadatumSizeLimitSpec :: Version -> Spec
+metadatumSizeLimitSpec v = do
+  let genBytes n = BS.pack <$> vectorOf n arbitrary
+      genAsciiText n = T.pack <$> vectorOf n (choose ('a', 'z'))
+      dec :: ToCBOR a => a -> Either DecoderError Metadatum
+      dec = decodeFull v . toLazyByteString . toCBOR . E
+  prop "Accepts bytes up to 64 bytes" $
+    forAll (choose (0, 64) >>= genBytes) $ \bs ->
```
Comment (lehins) [inline eras/shelley/impl/testlib/Test/Cardano/Ledger/Shelley/Binary/RoundTrip.hs]:
```suggestion
    forAll (choose (0, 64) >>= genByteString) $ \bs ->
```

File: eras/shelley/impl/testlib/Test/Cardano/Ledger/Shelley/Binary/RoundTrip.hs [hunk 8]
```diff
@@ -60,6 +68,34 @@ roundTripStateEraTypesSpec = do
     roundTripEraTypeSpec @era @EpochState
     roundTripEraTypeSpec @era @NewEpochState
 
+metadatumSizeLimitSpec :: Version -> Spec
+metadatumSizeLimitSpec v = do
+  let genBytes n = BS.pack <$> vectorOf n arbitrary
```
Comment (lehins) [inline eras/shelley/impl/testlib/Test/Cardano/Ledger/Shelley/Binary/RoundTrip.hs]: We have `genByteString` that is more efficient than that
```suggestion
  let
```

File: eras/shelley/impl/testlib/Test/Cardano/Ledger/Shelley/Binary/RoundTrip.hs [hunk 9]
```diff
@@ -60,6 +68,34 @@ roundTripStateEraTypesSpec = do
...
+      genAsciiText n = T.pack <$> vectorOf n (choose ('a', 'z'))
+      dec :: ToCBOR a => a -> Either DecoderError Metadatum
+      dec = decodeFull v . toLazyByteString . toCBOR . E
```
Comment (lehins) [inline eras/shelley/impl/testlib/Test/Cardano/Ledger/Shelley/Binary/RoundTrip.hs]: `E` is not necessary
```suggestion
      dec = decodeFull v . toLazyByteString . toCBOR
```

File: eras/shelley/impl/testlib/Test/Cardano/Ledger/Shelley/Binary/RoundTrip.hs [hunk 10]
```diff
@@ -60,6 +68,34 @@ roundTripStateEraTypesSpec = do
...
+  prop "Accepts bytes up to 64 bytes" $
+    forAll (choose (0, 64) >>= genBytes) $ \bs ->
+      dec bs `shouldSatisfy` isRight
+  prop "Accepts text up to 64 bytes" $
+    forAll (choose (0, 64) >>= genAsciiText) $ \txt ->
+      dec txt `shouldSatisfy` isRight
```
Comment (lehins) [inline eras/shelley/impl/testlib/Test/Cardano/Ledger/Shelley/Binary/RoundTrip.hs]: Could you please apply the same suggestion to all `shouldSatisfy`
```suggestion
      expectRightDeepExpr_ $ dec txt
```

File: eras/shelley/impl/testlib/Test/Cardano/Ledger/Shelley/Binary/RoundTrip.hs [hunk 11]
```diff
@@ -9,13 +9,19 @@
...
 ) where
 
 import Cardano.Ledger.Binary
 import Cardano.Ledger.Core
+import Cardano.Ledger.Metadata (Metadatum)
 import Cardano.Ledger.Shelley (ShelleyEra)
 import Cardano.Ledger.Shelley.LedgerState
 import Cardano.Ledger.Shelley.State
+import qualified Data.ByteString as BS
+import Data.Either (isLeft, isRight)
```
Comment (lehins) [inline eras/shelley/impl/testlib/Test/Cardano/Ledger/Shelley/Binary/RoundTrip.hs]: We have much better helpers for this already in scope: `expectRightDeepExpr_` and `expectLeftDeepExpr_`
```suggestion
```

File: eras/allegra/impl/testlib/Test/Cardano/Ledger/Allegra/Imp/UtxowSpec.hs [hunk 12]
```diff
@@ -1,46 +0,0 @@
...
-spec = describe "UTXOW" $ do
-  it "InvalidMetadata" $ do
-    invalidMetadatum <- genInvalidMetadata
-    let auxData = mkBasicTxAuxData & metadataTxAuxDataL .~ invalidMetadatum
-    let auxDataHash = hashTxAuxData auxData
-    let tx =
-          mkBasicTx mkBasicTxBody
-            & bodyTxL . auxDataHashTxBodyL .~ SJust auxDataHash
-            & auxDataTxL .~ SJust auxData
-    submitFailingTx tx [injectFailure InvalidMetadata]
```
Comment (lehins) [inline eras/allegra/impl/testlib/Test/Cardano/Ledger/Allegra/Imp/UtxowSpec.hs:36]: Why delete this test module? Could you please bring it back, but instead move it into shelley, since it is applicable to all eras.
It will be better to make it a successful test with `submitTx_`
Adding a comment saying that this check is done by the decoder instead of the rules.

**Review by lehins — CHANGES_REQUESTED** [review]
Looks good. However, one important fix is still missing, namely CDDL for Shelley era is not correct for metadata

File: eras/shelley/impl/testlib/Test/Cardano/Ledger/Shelley/Binary/RoundTrip.hs [hunk 13]
```diff
@@ -60,6 +65,34 @@ roundTripStateEraTypesSpec = do
...
+    forAll (choose (0, 64) >>= genByteString) $ \bs ->
+      expectRightDeepExpr_ $ dec bs
+  prop "Accepts text up to 64 bytes" $
+    forAll (choose (0, 64) >>= genAsciiText) $ \txt ->
+      expectRightDeepExpr_ $ dec txt
+  if v > natVersion @2
+    then do
+      prop "Rejects bytes exceeding 64 bytes" $
+        forAll (choose (65, 1000) >>= genByteString) $ \bs ->
+          void . expectLeftExpr $ dec bs
```
Comment (lehins) [inline eras/shelley/impl/testlib/Test/Cardano/Ledger/Shelley/Binary/RoundTrip.hs:84]: Why not `expectLeftDeepExpr_` as I suggested?
````suggestion
          expectLeftDeepExpr_ $ dec bs
```

File: eras/shelley/impl/testlib/Test/Cardano/Ledger/Shelley/Binary/RoundTrip.hs [hunk 14]
```diff
@@ -60,6 +65,34 @@ roundTripStateEraTypesSpec = do
...
+      prop "Rejects text exceeding 64 bytes" $
+        forAll (choose (65, 1000) >>= genAsciiText) $ \txt ->
+          void . expectLeftExpr $ dec txt
```
Comment (lehins) [inline eras/shelley/impl/testlib/Test/Cardano/Ledger/Shelley/Binary/RoundTrip.hs:87]: Ditto?
```suggestion
          expectDeepLeftExpr_ $ dec txt
```

**Review by lehins — APPROVED** [review]
Looks good. Thank you!

File: eras/shelley/impl/testlib/Test/Cardano/Ledger/Shelley/Binary/RoundTrip.hs (hunk 13 above)
Comment (Soupstraw) [reply eras/shelley/impl/testlib/Test/Cardano/Ledger/Shelley/Binary/RoundTrip.hs:84]: I tried, but it didn't work because `DecoderError` does not implement `NFData`

Comment (lehins) [reply eras/shelley/impl/testlib/Test/Cardano/Ledger/Shelley/Binary/RoundTrip.hs:84]: That's not nice. Thank you for pointing it out: https://github.com/IntersectMBO/cardano-base/issues/643
