### PR TITLE
Make decoders fail when encountering duplicate elements in `TxWits`

### LINKED ISSUE #4698: Disallow duplicate elements / keys in witnesses
Unfortunately due to the way Annotator works we were unable to prevent duplicates in witnesses for Conway. We do need to fix that for the future era.

Blocked by ~#4009~ #5363

### PR DESCRIPTION
**Pull request by Soupstraw**
# Description

This PR makes the decoders fail when encountering duplicate values in any of the sets in `TxWits`. I added some negative golden tests that try to decode witnesses with duplicate elements.

close https://github.com/IntersectMBO/cardano-ledger/issues/4698

# Checklist

- [ ] Commits in meaningful sequence and with useful messages.
- [ ] Tests added or updated when needed.
- [ ] `CHANGELOG.md` files updated for packages with externally visible changes.  
      **NOTE: _New section is never added with the code changes._** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#changelogmd)).
- [ ] Versions updated in `.cabal` and `CHANGELOG.md` files when necessary, according to the
      [versioning process](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process).
- [ ] Version bounds in `.cabal` files updated when necessary.  
      **NOTE: _If bounds change in a cabal file, that package itself must have a version increase._** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process)).
- [x] Code formatted (use `scripts/fourmolize.sh`).
- [x] Cabal files formatted (use `scripts/cabal-format.sh`).
- [x] CDDL files are up to date (use `scripts/gen-cddl.sh`)
- [x] [`hie.yaml`](https://github.com/intersectmbo/cardano-ledger/blob/master/hie.yaml) updated (use `scripts/gen-hie.sh`).
- [ ] Self-reviewed the diff.

### CODE REVIEW

File: eras/alonzo/impl/src/Cardano/Ledger/Alonzo/TxWits.hs [hunk 1]
```diff
@@ -579,55 +580,93 @@ instance
...
+      {-# INLINE noDuplicatesDatsDecoder #-}
+
+      noDuplicatesScriptsDecoder :: Decoder s (Annotator (Map ScriptHash (Script era)))
+      noDuplicatesScriptsDecoder = do
+        allowTag setTag
+        scripts <- decodeList $ fmap (fromNativeScript @era) <$> decCBOR
+        pure $ go Map.empty scripts
+        where
+          go m [] = pure m
+          go m (x : xs) = do
```
Comment (lehins) [inline eras/alonzo/impl/src/Cardano/Ledger/Alonzo/TxWits.hs]: We need to make sure we avoid space leaks and have decoders as performant as possible
```suggestion
          go !m (x : xs) = do
```

File: eras/alonzo/impl/src/Cardano/Ledger/Alonzo/TxWits.hs [hunk 2]
```diff
@@ -579,55 +580,93 @@ instance
...
+            x' <- x
+            let dh = hashData x'
+            if dh `Map.member` m
+              then fail $ "Duplicate dats found: " <> show dh
+              else go (Map.insert dh x' m) xs
+      {-# INLINE noDuplicatesDatsDecoder #-}
+
+      noDuplicatesScriptsDecoder :: Decoder s (Annotator (Map ScriptHash (Script era)))
```
Comment (lehins) [inline eras/alonzo/impl/src/Cardano/Ledger/Alonzo/TxWits.hs]: This only works for `NativeScript`s, which is not indicated anywhere in the name. Note that previously it was called: `nativeScriptsDecoder`.

File: eras/alonzo/impl/src/Cardano/Ledger/Alonzo/TxWits.hs [hunk 3]
```diff
@@ -579,55 +580,93 @@ instance
...
+          go m [] = pure m
+          go m (x : xs) = do
+            x' <- x
+            let sh = hashScript x'
+            if sh `Map.member` m
+              then fail $ "Duplicate scripts found: " <> show sh
+              else go (Map.insert sh x' m) xs
+      {-# INLINE noDuplicatesScriptsDecoder #-}
+
+      scriptsDecoder :: Decoder s (Annotator (Map ScriptHash (Script era)))
```
Comment (lehins) [inline eras/alonzo/impl/src/Cardano/Ledger/Alonzo/TxWits.hs]: Same here, it is only applicable to native scripts.

File: eras/alonzo/impl/src/Cardano/Ledger/Alonzo/TxWits.hs [hunk 4]
```diff
@@ -579,55 +580,93 @@ instance
         txWitnessField
         []
     where
+      setDecoder :: (Ord a, DecCBOR a) => Decoder s (Annotator (Set a))
+      setDecoder =
+        pure
+          <$> ifDecoderVersionAtLeast
+            (natVersion @12)
+            (decodeSetLikeEnforceNoDuplicates Set.insert (\s -> (length s, s)) decCBOR)
```
Comment (lehins) [inline eras/alonzo/impl/src/Cardano/Ledger/Alonzo/TxWits.hs]: You lost the check that Set must not be empty.
```suggestion
            (do 
            s <- decodeSetLikeEnforceNoDuplicates Set.insert (\s -> (length s, s)  decCBOR
            when (Set.null s) $ fail "Set cannot be empty"
            pure s
            )
```

File: eras/alonzo/impl/src/Cardano/Ledger/Alonzo/TxWits.hs [hunk 5]
```diff
@@ -579,55 +580,93 @@ instance
         txWitnessField
         []
     where
+      setDecoder :: (Ord a, DecCBOR a) => Decoder s (Annotator (Set a))
+      setDecoder =
```
Comment (lehins) [inline eras/alonzo/impl/src/Cardano/Ledger/Alonzo/TxWits.hs]: So, future reader doesn't loose this important detail
```suggestion
      nonEmptySetDecoder :: (Ord a, DecCBOR a) => Decoder s (Annotator (Set a))
      nonEmptySetDecoder =
```

File: eras/alonzo/impl/src/Cardano/Ledger/Alonzo/TxWits.hs [hunk 6]
```diff
@@ -579,55 +580,93 @@ instance
...
-      nativeScriptsDecoder :: Decoder s (Annotator (Map ScriptHash (Script era)))
-      nativeScriptsDecoder =
-        ifDecoderVersionAtLeast
-          (natVersion @9)
-          ( allowTag setTag
-              >> mapTraverseableDecoderA (decodeNonEmptyList pairDecoder) (Map.fromList . NE.toList)
-          )
-          (mapTraverseableDecoderA (decodeList pairDecoder) Map.fromList)
+      pairDecoder :: Decoder s (Annotator (ScriptHash, Script era))
+      pairDecoder = fmap (asHashedScriptPair @era . fromNativeScript) <$> decCBOR
```
Comment (lehins) [inline eras/alonzo/impl/src/Cardano/Ledger/Alonzo/TxWits.hs]: It used to be scoped to native script decoder only, which did not require a special naming, but now it is in a larger scope, which means it should have a proper name, something along the lines
```suggestion
      hashedNativeSciptDecoder = fmap (asHashedScriptPair @era . fromNativeScript) <$> decCBOR
```

File: eras/alonzo/impl/src/Cardano/Ledger/Alonzo/TxWits.hs [hunk 7]
```diff
@@ -579,55 +580,93 @@ instance
...
+      noDuplicatesScriptsDecoder = do
+        allowTag setTag
+        scripts <- decodeList $ fmap (fromNativeScript @era) <$> decCBOR
+        pure $ go Map.empty scripts
+        where
+          go m [] = pure m
+          go m (x : xs) = do
+            x' <- x
+            let sh = hashScript x'
+            if sh `Map.member` m
```
Comment (lehins) [inline eras/alonzo/impl/src/Cardano/Ledger/Alonzo/TxWits.hs]: This approach of checking membership on every insert is slower when compared to keeping track of the length and then failing when number of elements in the Map/Set is smaller than in the original list. We don't need to report the exact duplicate, this can be left up to the user to figure out. So, this is how I'd suggest to write it:
```haskell
          go (m, n) [] = do
            when (Map.size == 0) $ fail "Empty script Set is not allowed"
            when (Map.size /= n) $ fail "Duplicate elements in the scripts Set were encountered"
            pure m
          go (!m, !n) (x : xs) =
            go (Map.insert (hashScript x) x m, n + 1) xs

File: eras/alonzo/impl/src/Cardano/Ledger/Alonzo/TxWits.hs [hunk 8]
```diff
@@ -579,55 +580,93 @@ instance
...
+
+      noDuplicatesDatsDecoder :: Decoder s (Annotator (TxDats era))
+      noDuplicatesDatsDecoder = do
+        allowTag setTag
+        dats <- decodeList decCBOR
+        pure $ TxDats <$> go Map.empty dats
         where
-          pairDecoder :: Decoder s (Annotator (ScriptHash, Script era))
-          pairDecoder = fmap (asHashedScriptPair . fromNativeScript) <$> decCBOR
+          go m [] = pure m
```
Comment (lehins) [inline eras/alonzo/impl/src/Cardano/Ledger/Alonzo/TxWits.hs]: It is almost the same pattern as with scripts. This should be abstracted out to reduce duplication.

File: eras/alonzo/impl/src/Cardano/Ledger/Alonzo/TxWits.hs [hunk 9]
```diff
@@ -579,55 +580,93 @@ instance
...
+          go m (x : xs) = do
+            x' <- x
```
Comment (lehins) [inline eras/alonzo/impl/src/Cardano/Ledger/Alonzo/TxWits.hs]: This is incorrect. This means you are decoding `Either DecoderError (Data era)`, not `Data era`. Looks like we don't have any roundtrip tests for dijsktra era and you ended up disabling huddle tests in this PR.

Could you please add all the round trip tests. We are starting to change decoders functionality and we should not be doing that with relevant tests disabled.

File: eras/dijkstra/impl/test/Test/Cardano/Ledger/Dijkstra/Binary/CddlSpec.hs [hunk 10]
```diff
@@ -117,11 +117,12 @@ spec = do
       huddleRoundTripCborSpec @(Datum DijkstraEra) v "datum_option"
       -- TODO NoDatum is encoded as an empty bytestring
       xdescribe "fix NoDatum" $ huddleRoundTripArbitraryValidate @(Datum DijkstraEra) v "datum_option"
-      huddleRoundTripAnnCborSpec @(TxWits DijkstraEra) v "transaction_witness_set"
+      xdescribe "fix duplicates in maps" $ do
```
Comment (lehins) [inline eras/dijkstra/impl/test/Test/Cardano/Ledger/Dijkstra/Binary/CddlSpec.hs:121]: Why did you decide to disable those tests instead of fixing them in the same PR?

File: eras/dijkstra/impl/testlib/Test/Cardano/Ledger/Dijkstra/Binary/Golden.hs [hunk 11]
```diff
@@ -66,6 +70,84 @@ duplicateCertsTx v =
...
+  EraPlutusTxInfo l era =>
+  SLanguage l -> Enc
+witsDuplicatePlutus slang =
+  mconcat
+    [ E $ TkMapLen 1
+    , E @Int $ case slang of
+        SPlutusV1 -> 3
+        SPlutusV2 -> 6
+        SPlutusV3 -> 7
+        l -> error $ "Unsupported plutus version: " <> show l
```
Comment (lehins) [inline eras/dijkstra/impl/testlib/Test/Cardano/Ledger/Dijkstra/Binary/Golden.hs:115]: PlutusV4 is supported in Dijkstra. If some missing functionality is preventing us from setting `PlutusV4` here, could you please create a ticket about it.

File: eras/alonzo/impl/src/Cardano/Ledger/Alonzo/TxWits.hs [hunk 12]
```diff
@@ -579,55 +580,93 @@ instance
...
       txWitnessField 4 =
         fieldAA
           (\x wits -> wits {atwrDatsTxWits = x})
-          From
+          ( D $
+              ifDecoderVersionAtLeast
+                (natVersion @12)
+                noDuplicatesDatsDecoder
+                decCBOR
+          )
```
Comment (lehins) [inline eras/alonzo/impl/src/Cardano/Ledger/Alonzo/TxWits.hs]: This functionality should go into `DecCBOR (Annotator (TxDatsRaw era))` instance instead.

File: eras/alonzo/impl/src/Cardano/Ledger/Alonzo/TxWits.hs [hunk 13]
```diff
@@ -579,55 +580,93 @@ instance
...
+              then fail $ "Duplicate scripts found: " <> show sh
+              else go (Map.insert sh x' m) xs
+      {-# INLINE noDuplicatesScriptsDecoder #-}
+
+      scriptsDecoder :: Decoder s (Annotator (Map ScriptHash (Script era)))
+      scriptsDecoder =
+        ifDecoderVersionAtLeast
+          (natVersion @12)
+          noDuplicatesScriptsDecoder
+          (allowTag setTag >> mapTraverseableDecoderA (decodeList pairDecoder) Map.fromList)
```
Comment (lehins) [inline eras/alonzo/impl/src/Cardano/Ledger/Alonzo/TxWits.hs]: This is now wrong, because you lost enforcement of nonemptiedness. See implementation of `nativeScriptsDecoder`. I can also bet that this is the cause of the CI failure that you get on this PR.
```suggestion
          nativeScriptsDecoder
```

**Review by lehins — CHANGES_REQUESTED** [review]
There are quite a few problems in this PR unfortunately.
It does need a bit more work and more tests that check this functionality in Dijkstra.

File: eras/dijkstra/impl/test/Test/Cardano/Ledger/Dijkstra/Binary/CddlSpec.hs (hunk 10 above)
Comment (Soupstraw) [reply eras/dijkstra/impl/test/Test/Cardano/Ledger/Dijkstra/Binary/CddlSpec.hs:121]: This has to be fixed in Cuddle first. The problem is that the bytestrings that huddle generates for `omap`s contain duplicates, but we need overridable generators to actually fix that.

File: eras/alonzo/impl/src/Cardano/Ledger/Alonzo/TxWits.hs (hunk 7 above)
Comment (Soupstraw) [reply eras/alonzo/impl/src/Cardano/Ledger/Alonzo/TxWits.hs]: My thinking was that this way we can fail early without having to decode the entire map and `O(n log n)` vs `O(n)` is not going to make a huge difference at the sizes we're dealing with. I can change it to your solution though if you think it makes more sense to do it that way.

File: eras/dijkstra/impl/testlib/Test/Cardano/Ledger/Dijkstra/Binary/Golden.hs (hunk 11 above)
Comment (Soupstraw) [reply eras/dijkstra/impl/testlib/Test/Cardano/Ledger/Dijkstra/Binary/Golden.hs:115]: Done: https://github.com/IntersectMBO/cardano-ledger/issues/5403

File: eras/alonzo/impl/src/Cardano/Ledger/Alonzo/TxWits.hs (hunk 7 above)
Comment (Soupstraw) [reply eras/alonzo/impl/src/Cardano/Ledger/Alonzo/TxWits.hs]: But now that I think of it, scripts can be really small, so you could fit quite a bit of those into a transaction. In that case making the worst case as good as possible is a good idea.

File: eras/dijkstra/impl/test/Test/Cardano/Ledger/Dijkstra/Binary/CddlSpec.hs (hunk 10 above)
Comment (lehins) [reply eras/dijkstra/impl/test/Test/Cardano/Ledger/Dijkstra/Binary/CddlSpec.hs:121]: Got it. Thanks!

File: eras/alonzo/impl/src/Cardano/Ledger/Alonzo/TxWits.hs (hunk 7 above)
Comment (lehins) [reply eras/alonzo/impl/src/Cardano/Ledger/Alonzo/TxWits.hs]: > My thinking was that this way we can fail early without having to decode the entire map

We need to optimize our decoders for the positive case, when transaction is valid, because that the case that is being decoded the most. We don't need to worry ourselves too much about transactions that can't make it into the mempool due to them being malformed.

Naturally, we can't have dangerously slow decoders that fail decoding either, but that would be pretty hard to do anyways :grin:

File: eras/alonzo/impl/src/Cardano/Ledger/Alonzo/TxWits.hs (hunk 9 above)
Comment (Soupstraw) [reply eras/alonzo/impl/src/Cardano/Ledger/Alonzo/TxWits.hs]: The monad that `x` gets bound in is `Annotator`, not `Either DecoderError`, so the decoder is correctly decoding `Annotator (Data era)` as far as I can tell.

**Comment by lehins** [comment]
@Soupstraw Bunch of tests are still failing.

File: eras/alonzo/impl/src/Cardano/Ledger/Alonzo/TxWits.hs (hunk 9 above)
Comment (lehins) [reply eras/alonzo/impl/src/Cardano/Ledger/Alonzo/TxWits.hs]: I take it back. You are totally right! I forgot that I added `Monad` instance for `Annotator` :see_no_evil:

File: eras/alonzo/impl/src/Cardano/Ledger/Alonzo/TxWits.hs [hunk 14]
```diff
@@ -308,16 +309,46 @@ unTxDatsL :: forall era. Era era => Lens' (TxDats era) (Map DataHash (Data era))
...
+              >> mapTraverseableDecoderA
+                (decodeNonEmptyList decCBOR)
+                (TxDatsRaw . Map.fromElems hashData . NE.toList)
+          )
       )
       (mapTraverseableDecoderA (decodeList decCBOR) (TxDatsRaw . Map.fromElems hashData))
+    where
+      noDuplicatesDatsDecoder :: Decoder s (Annotator (TxDatsRaw era))
+      noDuplicatesDatsDecoder = (fmap . fmap) (TxDatsRaw @era) . noDuplicateNonEmptySetAsMapDecoderAnn $
+        \dat -> (hashData dat, dat)
```
Comment (lehins) [inline eras/alonzo/impl/src/Cardano/Ledger/Alonzo/TxWits.hs]: I think this will be slightly clearer and faster.
```suggestion
      noDuplicatesDatsDecoder = 
        coerce . noDuplicateNonEmptySetAsMapDecoderAnn $ \dat -> (hashData dat, dat)
```

File: eras/alonzo/impl/src/Cardano/Ledger/Alonzo/TxWits.hs [hunk 15]
```diff
@@ -579,55 +610,75 @@ instance
...
+        pure
+          <$> ifDecoderVersionAtLeast
+            (natVersion @12)
+            ( do
+                s <- decodeSetLikeEnforceNoDuplicates Set.insert (\s -> (length s, s)) decCBOR
+                when (Set.null s) $ fail "Set cannot be empty"
+                pure s
+            )
+            (allowTag setTag >> Set.fromList . NE.toList <$> decodeNonEmptyList decCBOR)
+      {-# INLINE nonEmptySetDecoder #-}
```
Comment (lehins) [inline eras/alonzo/impl/src/Cardano/Ledger/Alonzo/TxWits.hs]: Duplication can further be reduced:
Note that we don't have to use `mapTraverseableDecoderA (decodeList decCBOR) Set.fromList` anymore, because previously we only had an `Annotator` instance for address witnesses, but since #4938, we no longer have this restriction

```suggestion
      addrWitsSetDecoder :: (Ord a, DecCBOR a) => Decoder s (Annotator (Set a))
      addrWitsSetDecoder = pure <$> do
        let 
          nonEmptyDecoder = do
            allowTag setTag
            Set.fromList . NE.toList <$> decodeNonEmptyList decCBOR
          nonEmptyNoDuplicatesDecoder = do
              s <- decodeSetLikeEnforceNoDuplicates Set.insert (\s -> (length s, s)) decCBOR
              when (Set.null s) $ fail "Set cannot be empty"
              pure s
        ifDecoderVersionAtLeast
          (natVersion @9)
          (ifDecoderVersionAtLeast (natVersion @12) nonEmptyNoDuplicatesDecoder nonEmptyDecoder)
          (Set.fromList <$> decodeList decCBOR)
      {-# INLINE addrWitsSetDecoder #-}
```
I think it'll be easier to read too.

File: eras/alonzo/impl/src/Cardano/Ledger/Alonzo/TxWits.hs [hunk 16]
```diff
@@ -579,55 +610,75 @@ instance
...
           )
-          (mapTraverseableDecoderA (decodeList pairDecoder) Map.fromList)
         where
-          pairDecoder :: Decoder s (Annotator (ScriptHash, Script era))
-          pairDecoder = fmap (asHashedScriptPair . fromNativeScript) <$> decCBOR
+          ensureNonEmpty :: Annotator (Map ScriptHash (Script era)) -> Annotator (Map ScriptHash (Script era))
+          ensureNonEmpty x = do
+            x' <- x
+            when (null x') $ fail "Map not empty"
+            x
```
Comment (lehins) [inline eras/alonzo/impl/src/Cardano/Ledger/Alonzo/TxWits.hs]: Couple of things about this function:
* On the wire it is a Set
* we fail when it is empty, not when it is "not empty" :grin:
* Avoiding ticks is a good practice.
* you already run `x` action once, which means it is better to return the result, instead of running it again.
```suggestion
          ensureNonEmpty xAnn = do
            x <- xAnn
            when (null x) $ fail "Set is empty"
            pure x
```

File: eras/alonzo/impl/testlib/Test/Cardano/Ledger/Alonzo/Binary/Annotator.hs [hunk 17]
```diff
@@ -152,16 +153,23 @@ instance (AlonzoEraScript era, DecCBOR (NativeScript era)) => DecCBOR (AlonzoTxW
         txWitnessField
         []
     where
+      setDecoder :: (Ord a, DecCBOR a) => Decoder s (Set a)
+      setDecoder =
+        allowTag setTag
+          >> ifDecoderVersionAtLeast
+            (natVersion @12)
+            (decodeSetLikeEnforceNoDuplicates Set.insert (\s -> (length s, s)) decCBOR)
+            (Set.fromList . NE.toList <$> decodeNonEmptyList decCBOR)
```
Comment (lehins) [inline eras/alonzo/impl/testlib/Test/Cardano/Ledger/Alonzo/Binary/Annotator.hs]: Here too duplication can be reduced a bit more:
```suggestion
        ifDecoderVersionAtLeast
          (natVersion @9)
          (allowTag setTag
             >> ifDecoderVersionAtLeast
                (natVersion @12)
                (decodeSetLikeEnforceNoDuplicates Set.insert (\s -> (length s, s)) decCBOR)
                (Set.fromList . NE.toList <$> decodeNonEmptyList decCBOR)
                )
          (Set.fromList <$> decodeList decCBOR)
```

**Review by lehins — APPROVED** [review]
Very nice!
Thank you!

File: eras/alonzo/impl/src/Cardano/Ledger/Alonzo/TxWits.hs (hunk 16 above)
Comment (Soupstraw) [reply eras/alonzo/impl/src/Cardano/Ledger/Alonzo/TxWits.hs]: I ended up not needing this function, since I can actually fail in the `Decode` in this case

File: eras/alonzo/impl/src/Cardano/Ledger/Alonzo/TxWits.hs (hunk 15 above)
Comment (Soupstraw) [reply eras/alonzo/impl/src/Cardano/Ledger/Alonzo/TxWits.hs]: ~~I assume the `INLINE` pragma should stay in place?~~

Oh, I see, it's meant to replace `nonEmptySetDecoder`
