### PR TITLE
[872] Generate Delegation Certificates

### LINKED ISSUE #872: Generate _Delegate_ Certificates
Extend `genDCert` to also generate `Delegate` certs.

Do this in concert with testing the  property `credentialMappingAfterDelegation` against the LEDGER STS Trace generator.

### LINKED ISSUE #1039: Diagnose STS transition failure with QuickCheck Delegation generators / properties
[This patch](https://github.com/input-output-hk/cardano-ledger-specs/files/3886642/break_STS.patch.txt) can be applied to `master` (as of `8d6478ac`) with something like `cat ~/Downloads/break_STS.patch.txt | git am`.  Running `cabal v2-test delegation-test` should yield

```
    STS Rules - Pool Properties
      newly registered stake pool is added to appropriate state mappings:                     OK (45.10s)
          ✓ newly registered stake pool is added to appropriate state mappings passed 300 tests.
      retired stake pool is removed from appropriate state mappings and marked  for retiring: FAIL
        *** Failed! (after 1 test):
        Exception while generating shrink-list:
          applySTSIndifferently was called with an empty set of rules
          CallStack (from HasCallStack):
            error, called at src/Control/State/Transition.hs:178:17 in small-steps-0.1.0.0-inplace:Control.State.Transition
        Exception thrown while showing test case:
          applySTSIndifferently was called with an empty set of rules
          CallStack (from HasCallStack):
            error, called at src/Control/State/Transition.hs:178:17 in small-steps-0.1.0.0-inplace:Control.State.Transition

        Use --quickcheck-replay=882481 to reproduce.
```

- It's unclear to me why this occurs. If someone can look into this issue it would be great, so that I can jump over to the byron/consensus integration task.
- The current approach (on `master`) works around this issue by generating & shrinking `SourceSignalTarget POOL`. However as @uroboros pointed out, there are issues with shrinking a `[SourceSignalTarget sts]` because any shrunk signal can cause all subsequent sources & targets to become invalid (i.e. they will not match the resultant STS state obtained by applying the shrunk signal).
  - The approach in this patch doesn't have the issue of shrinking which the `SourceSignalTarget` gen/shrink approach has because of https://github.com/input-output-hk/cardano-ledger-specs/blob/cbf9bc9c730020adfa32e537ead3a426bbafd7d7/byron/semantics/executable-spec/src/Control/State/Transition/Trace/Generator/QuickCheck.hs#L126 use of `Trace.closure`, we should rebuild a `Trace` with internal consistency & validity.
  - One advantage of gen/shrinking `SourceSignalTarget` is that it's smaller and easier to read in a test-suite failure printout.
  - To address the unwieldiness of the full `Trace sts` we could extend `Control.State.Transition.Trace.Generator.QuickCheck.forAllTrace` to `forAllTraceShow` with an `(Trace sts -> String)` custom show function. This would resemble `forAllShrinkShow` from QuickCheck. The function could transform the Trace to `SourceSignalTarget POOL` and `show` it to ease the diagnosis of bad signals.

### PR DESCRIPTION
**Pull request by uroboros**
Closes #872 
Closes  #1039 

This PR
* generates Delegate certs (using QuickCheck)
* classify the trace to ensure that Delegate certs are being produced
* switch the LEDGER Trace Classifier to QuickCheck from Hedgehog (HH was still being used here due to #1039 which is resolved by this PR) 

@mhuesch #1039 had to do with the fact that the LEDGER STS needs an initial state but does not have an Initial Rule to produce that state, so we have to provide an Initial State generator. I amended the STS machinery to allow for this. 
(hence the error "applySTSIndifferently was called with an empty set of rules", which is trying to produce the initial state from an initial rule)

### CODE REVIEW

File: byron/semantics/executable-spec/src/Control/State/Transition/Trace/Generator/QuickCheck.hs [hunk 1]
```diff
@@ -144,7 +188,26 @@ onlyValidSignalsAreGenerated
...
+     , Show (State sts)
+     , Show (Signal sts)
+     )
+  => Word64
+  -- ^ Maximum trace length.
+  -> traceGenEnv
+  -> Maybe (IRC sts -> QuickCheck.Gen (Either [[STS.PredicateFailure sts]] (State sts)))
+  -- ^ Optional generator of STS initial state
+  -> QuickCheck.Property
+onlyValidSignalsAreGeneratedFromInitState maxTraceLength traceGenEnv genSt0 =
```
Comment (mgudemann) [inline byron/semantics/executable-spec/src/Control/State/Transition/Trace/Generator/QuickCheck.hs]: thisNameStrikesMeAsBeingSlightlyTooLongForNotBeingUsedInJava

File: shelley/chain-and-ledger/executable-spec/test/Generator/Core/QuickCheck.hs [hunk 2]
```diff
@@ -109,12 +110,12 @@ genUtxo0 lower upper = do
...
 mkGenesisLedgerState
-  :: LedgerEnv
-  -> Gen (UTxOState, DPState)
+  :: IRC LEDGER
+  -> Gen (Either a (UTxOState, DPState))
 mkGenesisLedgerState _ = do
   utxo0 <- genUtxo0 5 10
   let (LedgerState utxoSt dpSt _) = genesisState utxo0
-  pure (utxoSt, dpSt)
+  pure $ Right (utxoSt, dpSt)
```
Comment (mgudemann) [inline shelley/chain-and-ledger/executable-spec/test/Generator/Core/QuickCheck.hs]: why the type `Either` here?

File: byron/semantics/executable-spec/src/Control/State/Transition/Trace/Generator/QuickCheck.hs (hunk 1 above)
Comment (uroboros) [reply byron/semantics/executable-spec/src/Control/State/Transition/Trace/Generator/QuickCheck.hs]: iDefinitelyWontArgueWithThat ;)

File: shelley/chain-and-ledger/executable-spec/test/Generator/Core/QuickCheck.hs (hunk 2 above)
Comment (uroboros) [reply shelley/chain-and-ledger/executable-spec/test/Generator/Core/QuickCheck.hs]: I've added an explanatory comment

File: byron/semantics/executable-spec/src/Control/State/Transition/Trace/Generator/QuickCheck.hs [hunk 3]
```diff
@@ -91,16 +96,36 @@ trace
...
+traceFromInitState
+  :: forall sts traceGenEnv
+   . (HasTrace sts traceGenEnv, Show (Environment sts))
+  => Word64
+  -- ^ Maximum trace length.
+  -> traceGenEnv
+  -> Maybe (IRC sts -> QuickCheck.Gen (Either [[STS.PredicateFailure sts]] (State sts)))
+  -- ^ Optional generator of STS initial state
+  -> QuickCheck.Gen (Trace sts)
+traceFromInitState maxTraceLength traceGenEnv genSt0 = do
```
Comment (mhuesch) [inline byron/semantics/executable-spec/src/Control/State/Transition/Trace/Generator/QuickCheck.hs]: Nice! :clap:

File: shelley/chain-and-ledger/executable-spec/test/Generator/Delegation/QuickCheck.hs [hunk 4]
```diff
@@ -89,12 +92,11 @@ genDCert
...
-  QC.frequency [ (3, genRegKeyCert keys dState)
-               , (3, genDeRegKeyCert keys dState)
-               , (3, genRegPool keys vrfKeys dpState)
-               , (3, genRetirePool keys pparams pState slot)
-               , (1, pure Nothing)
+  QC.frequency [ (2, genRegKeyCert keys dState)
+               , (2, genRegPool keys vrfKeys dpState)
+               , (3, genDelegation keys dpState)
+               , (1, genDeRegKeyCert keys dState)
+               , (1, genRetirePool keys pparams pState slot)
```
Comment (mhuesch) [inline shelley/chain-and-ledger/executable-spec/test/Generator/Delegation/QuickCheck.hs]: 👍

File: shelley/chain-and-ledger/executable-spec/test/Generator/Delegation/QuickCheck.hs [hunk 5]
```diff
@@ -141,7 +170,7 @@ genRegPool
 genRegPool keys vrfKeys dpState =
   if null availableKeys || null availableVrfKeys
      then pure Nothing
-     else do
+     else
        Just <$> genDCertRegPool availableKeys availableVrfKeys
```
Comment (mhuesch) [inline shelley/chain-and-ledger/executable-spec/test/Generator/Delegation/QuickCheck.hs]: 👍

File: shelley/chain-and-ledger/executable-spec/test/Rules/TestLedger.hs [hunk 6]
```diff
@@ -134,22 +133,9 @@ registeredPoolIsAdded = do
...
-
-shrinkPoolSST :: [SourceSignalTarget POOL] -> [[SourceSignalTarget POOL]]
-shrinkPoolSST = QC.shrinkList shrinker
- where
-  shrinker :: SourceSignalTarget POOL -> [SourceSignalTarget POOL]
-  shrinker (SourceSignalTarget src tgt sig) =
-    [ SourceSignalTarget src tgt sig' | sig' <- shrinkDCert sig ]
+    TQC.forAllTraceFromInitState traceLen traceLen (Just GQ.mkGenesisLedgerState) $ \tr ->
+      let sst = concatMap ledgerToPoolSsts (sourceSignalTargets tr)
+        in TestPool.poolIsMarkedForRetirement sst
```
Comment (mhuesch) [inline shelley/chain-and-ledger/executable-spec/test/Rules/TestLedger.hs]: Thanks, this is much more terse and also should shrink property 🙂
