### PR TITLE
Make IncompleteWithdrawals more informative

### LINKED ISSUE #5452: Improve `IncompleteWithdrawals` failure by adding current balance
I've been made aware that it would be very useful to learn what the actual balance of the account is when withdrawal fails.

In order to make this happen we need to change `ShelleyIncompleteWithdrawals` and `ConwayIncompleteWithdrawals` from `Withdrawals` to `Map (Credential Staking) (Mismatch RelEQ Coin)`
Also `withdrawalsThatDoNotDrainAccounts` will need to report the current balance as well, so it's signature will change to:
```haskell
withdrawalsThatDoNotDrainAccounts ::
  EraAccounts era =>
  Withdrawals ->
  Network ->
  Accounts era ->
  Maybe (Withdrawals, Map (Credential Staking) (Mismatch RelEQ Coin))
```

### PR DESCRIPTION
**Pull request by Soupstraw**
# Description

This PR modifies `ShelleyIncompleteWithdrawals` and `ConwayIncompleteWithdrawals` predicate failures so that they also show the expected withdrawal amount.

close https://github.com/IntersectMBO/cardano-ledger/issues/5452

# Checklist

- [x] Commits in meaningful sequence and with useful messages.
- [x] Tests added or updated when needed.
- [x] `CHANGELOG.md` files updated for packages with externally visible changes.  
      **NOTE: _New section is never added with the code changes._** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#changelogmd)).
- [x] Versions updated in `.cabal` and `CHANGELOG.md` files when necessary, according to the
      [versioning process](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process).
- [x] Version bounds in `.cabal` files updated when necessary.  
      **NOTE: _If bounds change in a cabal file, that package itself must have a version increase._** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process)).
- [x] Code formatted (use `scripts/fourmolize.sh`).
- [x] Cabal files formatted (use `scripts/cabal-format.sh`).
- [x] CDDL files are up to date (use `scripts/gen-cddl.sh`)
- [x] [`hie.yaml`](https://github.com/intersectmbo/cardano-ledger/blob/master/hie.yaml) updated (use `scripts/gen-hie.sh`).
- [x] Self-reviewed the diff.

### CODE REVIEW

File: eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Certs.hs [hunk 1]
```diff
@@ -234,7 +235,9 @@ conwayCertsTransition = do
           failOnJust
             (withdrawalsThatDoNotDrainAccounts withdrawals network accounts)
             ( \(invalid, incomplete) ->
-                WithdrawalsNotInRewardsCERTS $ Withdrawals $ unWithdrawals invalid <> unWithdrawals incomplete
+                WithdrawalsNotInRewardsCERTS $
+                  Withdrawals $
+                    unWithdrawals invalid <> fmap mismatchSupplied incomplete
```
Comment (Soupstraw) [inline eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Certs.hs:240]: I switched the domain of the `Map` in the failure  from `Credential` to `RewardAddress` to avoid having to use `mapKeys` here. I can revert the commit, but then we'll have to put up with an extra `mapKeys` here (`mapKeysMonotonic` should also be safe to use)

**Review by lehins — APPROVED** [review]
Perfect! Thank you!
