### PR TITLE
remove stake cert pointers on dereg

### LINKED ISSUE #785: Stake Key Deregistration - wrong pointer
In the ` Deleg-Dereg` rule of the `DELEG` transition, the stake registration certificate pointers are not properly being removed (in both the formal spec and the exec model). It is removing the `ptr` in the environment, which is actually the transaction pointer and not the certificate pointer. The type checker did not catch this since both are just aliases of `NxNxN`.

### PR DESCRIPTION
**Pull request by JaredCorduan**
The `DELEG` transition now properly removes the stake registration certificate pointers on the de-registration of a key.

I added the range exclusion operator (`⋫` or `|/>`) to the `Ledger.Core` `Relation` class.

Both the formal spec and the exec model now remove the cert prt with `ptrs ⋫ {hk}`.

I found another small fix, namely the `UTXO` rule was not allowing zero-valued coins, so now it does.

I added an example (`2J`) which drains a reward account and then de-registers a stake key.

unrelated to the main issue, I made the protocol update example (example 3) a bit more interesting by also voting on extra entropy. This value is a bit special, since after a successful vote, it injects itself into the next epoch nonce and is then set back to the neutral element in the protocol parameters.

closes #785

### CODE REVIEW

File: shelley/chain-and-ledger/executable-spec/src/STS/Utxo.hs [hunk 1]
```diff
@@ -95,7 +95,7 @@ utxoInductive = do
   ups' <- trans @(UP hashAlgo dsignAlgo) $ TRC ((slot_, pp, dms_), u ^. ups, txup tx)
 
   let outputCoins = [c | (TxOut _ c) <- Set.toList (range (txouts txBody))]
-  all (0<) outputCoins ?! NonPositiveOutputsUTxO
+  all (0 <=) outputCoins ?! NonPositiveOutputsUTxO
```
Comment (mgudemann) [inline shelley/chain-and-ledger/executable-spec/src/STS/Utxo.hs]: nitpick: should we then also rename the error slightly, e.g., `NegativeOutputsUTxO` ?

Comment (JaredCorduan) [reply shelley/chain-and-ledger/executable-spec/src/STS/Utxo.hs]: yes!
