### PR TITLE
Disable old redeemer deserialization

### LINKED ISSUE #5345: Remove support for invalid Redeemer serialization
Originally in Alonzo redeemers received an incorrect serialization specification,
which was fixed in Conway, but we had to support the incorrect one for the purpose of transitional backwards compatibility:

https://github.com/IntersectMBO/cardano-ledger/blob/24ef1741c5e0109e4d73685a24d8e753e225656d/eras/conway/impl/cddl-files/conway.cddl#L678-L685

It can now be removed in Dijkstra. CDDL has already been adjusted, but deserializers have not. 

Most likely we will have to redefine witnesses in Dijkstra from scratch, so we deserializers will be re-written. This ticket is here, so we do not forget to remove this old format

### PR DESCRIPTION
**Pull request by Soupstraw**
# Description

This PR disables the deprecated list deserializer for `Redeemers`.

close https://github.com/IntersectMBO/cardano-ledger/issues/5345

# Checklist

- [ ] Commits in meaningful sequence and with useful messages.
- [ ] Tests added or updated when needed.
- [ ] `CHANGELOG.md` files updated for packages with externally visible changes.  
      **NOTE: _New section is never added with the code changes._** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#changelogmd)).
- [ ] Versions updated in `.cabal` and `CHANGELOG.md` files when necessary, according to the
      [versioning process](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process).
- [ ] Version bounds in `.cabal` files updated when necessary.  
      **NOTE: _If bounds change in a cabal file, that package itself must have a version increase._** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process)).
- [x] Code formatted (use `scripts/fourmolize.sh`).
- [x] Cabal files formatted (use `scripts/cabal-format.sh`).
- [x] CDDL files are up to date (use `scripts/gen-cddl.sh`)
- [x] [`hie.yaml`](https://github.com/intersectmbo/cardano-ledger/blob/master/hie.yaml) updated (use `scripts/gen-hie.sh`).
- [ ] Self-reviewed the diff.

### CODE REVIEW

**Review by lehins — COMMENTED** [review]
That's exactly what we needed. Could I ask you to add a test case that ensures this behavior for Conway and Dijkstra differs and  doesn't change with time?

File: eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Binary/Golden.hs [hunk 1]
```diff
@@ -0,0 +1,107 @@
...
+    [ E (TkListLen 1)
+    , mconcat
+        [ E (TkListLen 4)
+        , E (0 :: Int)
+        , E (0 :: Int)
+        , E (0 :: Int)
+        , mconcat
+            [ E (TkListLen 2)
+            , E (0 :: Int)
+            , E (0 :: Int)
```
Comment (lehins) [inline eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Binary/Golden.hs]: It is easier for debugging to use different values, when somehting goes wrong
```suggestion
        , E (10 :: Int)
        , E (20 :: Int)
        , mconcat
            [ E (TkListLen 2)
            , E (30 :: Int)
            , E (40 :: Int)
```

File: eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Binary/Golden.hs [hunk 2]
```diff
@@ -0,0 +1,107 @@
...
+        ]
+    ]
+
+goldenListRedeemers :: forall era. ConwayEraTest era => Spec
+goldenListRedeemers =
+  it "Decoding Redeemers encoded as a list succeeds" $
+    expectDecoderResultOn @(Redeemers era)
+      (eraProtVerLow @era)
+      listRedeemersEnc
+      (Redeemers $ Map.singleton (SpendingPurpose $ AsIx 0) (Data $ I 0, ExUnits 0 0))
```
Comment (lehins) [inline eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Binary/Golden.hs]: To match my other comment
```suggestion
      (Redeemers $ Map.singleton (SpendingPurpose $ AsIx 10) (Data $ I 20, ExUnits 30 40))
```

File: eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Binary/Golden.hs [hunk 3]
```diff
@@ -0,0 +1,107 @@
...
+      (\(Redeemers m) -> m)
```
Comment (lehins) [inline eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Binary/Golden.hs]: There is already a helper like this
```suggestion
      unRedeemers
```

File: eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Binary/Golden.hs [hunk 4]
```diff
@@ -0,0 +1,107 @@
...
+ )
+import Cardano.Ledger.Alonzo.Scripts (ExUnits (..))
+import Cardano.Ledger.Alonzo.TxWits (Redeemers (..))
+import Cardano.Ledger.BaseTypes (Version)
+import Cardano.Ledger.Binary (
+  Annotator (..),
+  DecCBOR (..),
+  ToCBOR (..),
+  decodeFullAnnotator,
+  toStrictByteString,
```
Comment (lehins) [inline eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Binary/Golden.hs]: Could I ask you to re-export `toLazyByteString` from `Cardano.Ledger.Binary.Decoding.Annotated`. It is defined `Codec.CBOR.Write`, just like  `toStrictByteString`
```suggestion
  toLazyByteString,
```

File: eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Binary/Golden.hs [hunk 5]
```diff
@@ -0,0 +1,107 @@
...
+  Expectation
+expectDecoderFailure version enc expectedErr =
+  case result of
+    Left err -> err `shouldBe` expectedErr
+    Right x ->
+      expectationFailure $
+        "Expected a failure, but decoder succeeded:\n"
+          <> showExpr x
+  where
+    bytes = fromStrict . toStrictByteString $ toCBOR enc
```
Comment (lehins) [inline eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Binary/Golden.hs]: With my other suggestion. Otherwise this will result in redundant copies in memory and more code.
```suggestion
    bytes = toLazyByteString $ toCBOR enc
```

File: eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Binary/Golden.hs [hunk 6]
```diff
@@ -0,0 +1,107 @@
...
+expectDecoderResultOn ::
+  forall a b.
+  (ToExpr b, DecCBOR (Annotator a), Typeable a, Eq b) =>
+  Version -> Enc -> a -> (a -> b) -> Expectation
+expectDecoderResultOn version enc expected f =
+  case result of
+    Left err -> expectationFailure $ "Decoder failed with:\n" <> show err
+    Right x -> f x `shouldBeExpr` f expected
+  where
+    bytes = fromStrict . toStrictByteString $ toCBOR enc
```
Comment (lehins) [inline eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Binary/Golden.hs]: Ditto
```suggestion
    bytes = toLazyByteString $ toCBOR enc
```

File: eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Binary/Golden.hs [hunk 7]
```diff
@@ -0,0 +1,107 @@
...
+    result = decodeFullAnnotator @a version (label $ Proxy @(Annotator a)) decCBOR bytes
```
Comment (lehins) [inline eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Binary/Golden.hs]: There is already a helper that will do all of this and a bit more (it will also check that CBOR is well formed)
```suggestion
  embedTripAnnExpectation version version (\x _ -> f x `shouldBeExpr` f expected) Enc
```

File: eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Binary/Golden.hs [hunk 8]
```diff
@@ -0,0 +1,107 @@
...
+      expectationFailure $
+        "Expected a failure, but decoder succeeded:\n"
+          <> showExpr x
+  where
+    bytes = fromStrict . toStrictByteString $ toCBOR enc
+    result = decodeFullAnnotator @a version (label $ Proxy @(Annotator a)) decCBOR bytes
+
+expectDecoderResultOn ::
+  forall a b.
+  (ToExpr b, DecCBOR (Annotator a), Typeable a, Eq b) =>
```
Comment (lehins) [inline eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Binary/Golden.hs]: It's critical to add `HasCallStack` to test helpers like that, otherwise test failures will be reported in wrong place
```suggestion
  (ToExpr b, DecCBOR (Annotator a), Typeable a, Eq b, HasCallStack) =>
```

File: eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Binary/Golden.hs [hunk 9]
```diff
@@ -0,0 +1,107 @@
...
+  it,
+  shouldBe,
+  shouldBeExpr,
+  showExpr,
+ )
+import Test.Cardano.Ledger.Conway.Era (ConwayEraTest)
+
+expectDecoderFailure ::
+  forall a.
+  (ToExpr a, DecCBOR (Annotator a), Typeable a) =>
```
Comment (lehins) [inline eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Binary/Golden.hs]: Ditto
```suggestion
  (ToExpr a, DecCBOR (Annotator a), Typeable a, HasCallStack) =>
```

**Review by lehins — APPROVED** [review]
This is very nice!!! Thank you!
I only added suggestions with minor improvements.
