### PR TITLE
Fix transVITime to use open upper bound.

### LINKED ISSUE #3043: Incorrect conversion of validity interval's upper bound
Recently, we have switched to cardano-ledger in plutus-apps instead of using our own validation rules. We have found that `transVITime` behaviour seems to be incorrect.

It takes the upper bound and uses `PV1.to` function that creates a closed upper bound.
```
transVITime pp ei sysS (ValidityInterval SNothing (SJust i)) = do
  t <- slotToPOSIXTime pp ei sysS i
  pure $ PV1.to t

...

to :: a -> Interval a
to s = Interval (LowerBound NegInf True) (upperBound s)

upperBound :: a -> UpperBound a
upperBound a = UpperBound (Finite a) True -- Boolean flag, whether a bound is inclusive or not.
```

While the validity interval is defined as a half open interval, open on the top.

```
-- | ValidityInterval is a half open interval. Closed on the bottom, open on the top.
--   A SNothing on the bottom is negative infinity, and a SNothing on the top is positive infinity
data ValidityInterval = ValidityInterval
  { invalidBefore :: !(StrictMaybe SlotNo),
    invalidHereafter :: !(StrictMaybe SlotNo)
  }
```

The proper implementation should be 

```
transVITime pp ei sysS (ValidityInterval SNothing (SJust i)) = do
  t <- slotToPOSIXTime pp ei sysS i
  pure $
    PV1.Interval
      (PV1.LowerBound PV1.NegInf True)
      (PV1.strictUpperBound t)
```

It seems it can't be easily fixed as it would change the on-chain behaviour.

### PR DESCRIPTION
**Pull request by ghost**
This PR fixes #3043.

I have tried to use the Hardforks technique mentioned here https://github.com/input-output-hk/cardano-ledger/issues/3043#issuecomment-1319944707.

### CODE REVIEW

File: eras/alonzo/impl/src/Cardano/Ledger/Alonzo/PlutusScriptApi.hs [hunk 1]
```diff
@@ -165,7 +165,7 @@ collectTwoPhaseScriptInputs ei sysS pp tx utxo =
             (Right [])
   where
     scriptsAvailable = txscripts utxo tx
-    txinfo lang = txInfo lang ei sysS utxo tx
+    txinfo lang = txInfo pp lang ei sysS utxo tx
```
Comment (koslambrou) [inline eras/alonzo/impl/src/Cardano/Ledger/Alonzo/PlutusScriptApi.hs:168]: `pp` doesn't seem to be used anywhere. Change to `_pp`?

Comment (JaredCorduan) [reply eras/alonzo/impl/src/Cardano/Ledger/Alonzo/PlutusScriptApi.hs:168]: it's being used by `transVITime` so that it can switch on the major protocol version.

**Review by JaredCorduan — APPROVED** [review]
This looks great to me @ak3n , thank you!

File: eras/alonzo/impl/src/Cardano/Ledger/Alonzo/PlutusScriptApi.hs (hunk 1 above)
Comment (koslambrou) [reply eras/alonzo/impl/src/Cardano/Ledger/Alonzo/PlutusScriptApi.hs:168]: Oh sorry, I misread the implementation :D

**Comment by JaredCorduan** [comment]
@ak3n - let's add something to the CHANGLOG.md about this great fix. You can add it to `### Fixed` in the `## [Unreleased]` section.

File: eras/shelley/impl/src/Cardano/Ledger/Shelley/HardForks.hs [hunk 2]
```diff
@@ -57,3 +58,11 @@ forgoRewardPrefilter ::
   pp ->
   Bool
 forgoRewardPrefilter pp = pvMajor (getField @"_protocolVersion" pp) > natVersion @6
+
+-- | Starting with protocol version 9, we translate the upper bound of validity interval
+-- correctly for Plutus scripts.
```
Comment (JaredCorduan) [inline eras/shelley/impl/src/Cardano/Ledger/Shelley/HardForks.hs:63]:
```suggestion
-- correctly for Plutus scripts.
--
-- TODO - After mainnet has successfully moved to protocol version 9, we can check
-- to see if the semantic difference here has even been exercised.
-- (We probably also need to check preprod and potentially preview.)
-- If it has not been exercised by version 9, we can safely remove this check
-- and always use the correct semantics (which cleans up the code).
```

**Comment by ghost** [comment]
@JaredCorduan added the line to changelog. Have no idea what's wrong with the ci...

**Comment by JaredCorduan** [comment]
> @JaredCorduan added the line to changelog. Have no idea what's wrong with the ci...

thank you! the failure in cicero on the darwin machine has nothing to do with your changes, it's currently just a very flaky job.

**Comment by ghost** [comment]
@JaredCorduan thank you!
