### PR TITLE
[1084] Fixed and improved trace shrinker

### LINKED ISSUE #1084: Write a proper transaction shrinker
The current Tx shrinker does not shrink to valid transactions

### PR DESCRIPTION
**Pull request by uroboros**
Closes #1084 

This PR 

* fixes a bug in the trace shrinker (signals were passed in OldestFirst order to `Trace.closure` which expects NewestFirst)
* write a custom shrinker signal shrinker (replaces shrinkList) that preserves the leading signal during trace shrinking

This PR was intended to close #1084 which was about improving the Tx shrinker. On closer inspection the next bottleneck was _trace_ shrinking - since at this stage we're only producing Txs with single certificates and outputs, the options for shrinking are very limited. 

The remaining Tx shrinking work should be done as part of #868 and #877 (when we add multiple certs we can shrink them in a Tx, same with outputs)

### CODE REVIEW

File: byron/semantics/executable-spec/src/Control/State/Transition/Trace/Generator/QuickCheck.hs [hunk 1]
```diff
@@ -196,14 +197,27 @@ shrinkTrace
...
     st0 = Trace._traceInitState tr
-    signals = Trace.traceSignals Trace.OldestFirst tr
-    traceSignalsShrinks =
-      QuickCheck.shrinkList (shrinkSignal @sts @traceGenEnv) signals
+    signals = Trace.traceSignals Trace.NewestFirst tr
+
+    compareLen a b = compare (length a) (length b) -- ascending sort 
+    shrunk = sortBy compareLen (shrinkSignals signals)
+
+    shrinkSignals (sn:_last:[]) =
```
Comment (dnadales) [inline byron/semantics/executable-spec/src/Control/State/Transition/Trace/Generator/QuickCheck.hs]: This looks a bit convoluted. The problem is that the the shrinks are passed to `closure` in the reverse order. So isn't it sufficient to apply `reverse` to the these shrinks?

File: byron/semantics/executable-spec/src/Control/State/Transition/Trace/Generator/QuickCheck.hs [hunk 2]
```diff
@@ -196,14 +197,27 @@ shrinkTrace
...
   where
     env = Trace._traceEnv tr
     st0 = Trace._traceInitState tr
-    signals = Trace.traceSignals Trace.OldestFirst tr
-    traceSignalsShrinks =
-      QuickCheck.shrinkList (shrinkSignal @sts @traceGenEnv) signals
+    signals = Trace.traceSignals Trace.NewestFirst tr
+
+    compareLen a b = compare (length a) (length b) -- ascending sort 
+    shrunk = sortBy compareLen (shrinkSignals signals)
```
Comment (mgudemann) [inline byron/semantics/executable-spec/src/Control/State/Transition/Trace/Generator/QuickCheck.hs]: wouldn't `sortOn length (shrinkSignals signals)` also work?

[the remark this answers is not in the document]
Comment (uroboros) [reply byron/semantics/executable-spec/src/Control/State/Transition/Trace/Generator/QuickCheck.hs]: I'm sorting from most aggressive to least aggressive shrinks

File: byron/semantics/executable-spec/src/Control/State/Transition/Trace/Generator/QuickCheck.hs (hunk 1 above)
Comment (uroboros) [reply byron/semantics/executable-spec/src/Control/State/Transition/Trace/Generator/QuickCheck.hs]: here I'm not only fixing the order bug, but also writing a custom signal list shrinker (the goal of this PR). I've added commentary to the shrinkers, have a look and see if that clarifies my intent of my folly ;)

File: byron/semantics/executable-spec/src/Control/State/Transition/Trace/Generator/QuickCheck.hs (hunk 2 above)
Comment (uroboros) [reply byron/semantics/executable-spec/src/Control/State/Transition/Trace/Generator/QuickCheck.hs]: nice, thanks!

File: byron/semantics/executable-spec/src/Control/State/Transition/Trace/Generator/QuickCheck.hs [hunk 3]
```diff
@@ -188,22 +189,44 @@ forAllTrace
...
+
+    -- Shrink a list of signals such that we preserve the most recent signal in the shrunk lists.
+    -- This shrinker
+    --   - recursively omits all but the most recent signal
+    --   - builds up lists of signals starting with the most recent signal and
+    --     building up a list excluding the first (oldest) signal
+    shrinkSignals (sn:_last:[]) =
+      [[sn]]
+    shrinkSignals (sn:sm:sigs) =
+      [[sn]] -- a trace with only the most recent signal
```
Comment (dnadales) [inline byron/semantics/executable-spec/src/Control/State/Transition/Trace/Generator/QuickCheck.hs]: Why will this provide a meaningful shrink? If we take the newest signal (the last signal we apply) and apply it to `s0` that signal will probably need state information that won't be in `s0`. So it seems `closure` would fail and we will be performing unnecessary work.

Comment (uroboros) [reply byron/semantics/executable-spec/src/Control/State/Transition/Trace/Generator/QuickCheck.hs]: yes the shrink to [sn] has a low likelihood to succeed but has a high pay-off, so I think it's worth trying. (also `closure` just ignores signals that fail on some STS predicate, so it's ok on that front)

File: byron/semantics/executable-spec/src/Control/State/Transition/Trace/Generator/QuickCheck.hs (hunk 2 above)
Comment (dnadales) [reply byron/semantics/executable-spec/src/Control/State/Transition/Trace/Generator/QuickCheck.hs]: So for the record, would any of you care to make an issue to remove the use of `sort` and instead swap two lines to produce sorted shrinks? (And also add a QC property to `shrinkSignals` to make sure the shrinks produced are always sorted on the list length).

```
shrinkSignals (sn:_last:[]) = [[sn]]
shrinkSignals (sn:sm:sigs) =
  [[sn]] -- a trace with only the most recent signal
  ++ ((sn:) <$> shrinkSignals (sm:sigs)) -- shrink the tail
  ++ [sn:sigs] -- discard the second most recent signal  
-- shrink to [] if there is one or no signals
shrinkSignals _  = []
```

And for the record 2, also note that the shrink strategy is too aggressive. According to @uroboros that gave you guys good results, but if you start getting only very large counterexamples you might consider being a bit more conservative in the shrinker.

Comment (uroboros) [reply byron/semantics/executable-spec/src/Control/State/Transition/Trace/Generator/QuickCheck.hs]: nice one! #1103

Comment (dnadales) [reply byron/semantics/executable-spec/src/Control/State/Transition/Trace/Generator/QuickCheck.hs]: :ok_hand:
