### PR TITLE
Fixes the Byron-Shelley implementation of the PVBUMP STS

### LINKED ISSUE #471: Fix Byron-Shelley PVBUMP STS implementation
The implementation of the `PVBUMP` STS for the Byron-Shelley era specification is incorrect in that it considers proposals up to slot `s_n`, while it should have been `s_n - 2*k`. A fix should address this incorrect range.

### PR DESCRIPTION
**Pull request by mdimjasevic**
Per issue #471, this fixes the implementation of the `PVBUMP` STS in the Byron-Shelley era. A wrong slot window was considered.

Closes #471.

### CODE REVIEW

File: byron/ledger/executable-spec/src/Ledger/Update.hs [hunk 1]
```diff
@@ -854,7 +854,7 @@ instance STS PVBUMP where
   transitionRules =
     [ do
         TRC ((s_n, fads), (pv, pps), ()) <- judgmentContext
-        let r = filter ((<= s_n) . fst) fads
+        let r = filter ((\(Slot s) -> s <= (unSlot s_n) - 2 * (unBlockCount k)) . fst) fads
```
Comment (dnadales) [inline byron/ledger/executable-spec/src/Ledger/Update.hs]: What about writing something like

```haskell
let 
  firstStableSlot = unSlot s_n - 2 * (unBlockCount k)
  r = filter ((<= firstStableSlot) . unSlot . fst)
```

Comment (mdimjasevic) [reply byron/ledger/executable-spec/src/Ledger/Update.hs]: Thanks, that improves readability! Done.
