### PR TITLE
Fix errors discovered during conformance testing

### LINKED ISSUE #623: Merge update-confirmation and adoption thresholds
We can have a single threshold to be used for confirmation and adoption.
Having this reduces the space of possibilities we need to test, and
simplifies the update mechanism further.

### PR DESCRIPTION
**Pull request by dnadales**
Fix errors discovered during conformance testing of valid chains against the implementation in `cardano-ledger`.

- Fix the implementation of `PVBUMP`: the last proposal was being taken instead of the first one.
- Simplify the `EPOCH` rule.
- Count the block endorsement when registering it.
- Remove `cfmThd` use `upAdptThd` instead, since these are the same value, and we have no compelling reasons for using different ones here. This closes #623 
- Perform application version change, even when there are not votes in the block.
- Generate the update id's based on the `pwd` set (otherwise we would be generating duplicated proposal id's).
- Add a constant `c` to `GlobalParams` which is used to bound the concrete size. We use this constant when choosing the next `B` factor, and when elaborating this factor into a concrete one.

### CODE REVIEW

File: byron/ledger/executable-spec/src/Ledger/Update.hs [hunk 1]
```diff
@@ -1437,24 +1476,19 @@ instance STS PVBUMP where
...
         TRC ((s_n, fads, k), (pv, pps), ()) <- judgmentContext
-        let
-          mFirstStableSlot = minusSlotMaybe s_n (SlotCount . (2 *) . unBlockCount $ k)
-          r = case mFirstStableSlot of
-                Nothing -> []
-                Just s  -> filter ((<= s) . fst) fads
-        if r == []
-          then pure $! (pv, pps)
-          else do
-            let (_, (pv_c, pps_c)) = last r
```
Comment (dnadales) [inline byron/ledger/executable-spec/src/Ledger/Update.hs]: "The last shall be first"

image

File: byron/ledger/executable-spec/src/Ledger/Core.hs [hunk 2]
```diff
@@ -374,12 +385,42 @@ instance Relation (Set (a, b)) where
...
+  s ◁ r = filter ((`Set.member` toSet s) . fst) r
+
+  s ⋪ r = filter ((`Set.notMember` toSet s) . fst) r
+
+  r ▷ s = filter ((`Set.notMember` toSet s) . snd) r
+
+  (∪) = (++)
+
+  -- In principle a list of pairs allows for duplicated keys.
+  d0 ⨃ d1 = d0 ++ toList d1
```
Comment (uroboros) [inline byron/ledger/executable-spec/src/Ledger/Core.hs]: the same is true for `instance Relation (Set (a, b))` (we can have duplicate keys but distinct pairs) - and in that case we do still take care to exclude `dom d1` from `d0` - we could do the same here

File: byron/ledger/executable-spec/src/Ledger/Update.hs (hunk 1 above)
Comment (uroboros) [reply byron/ledger/executable-spec/src/Ledger/Update.hs]: Amen

File: byron/ledger/executable-spec/src/Ledger/Update.hs [hunk 3]
```diff
@@ -718,15 +716,15 @@ delegationMap (_, dms, _, _) = dms
...
-  ( (ProtVer, PParams)
-  , [(Core.Slot, (ProtVer, PParams))]
-  , Map ApName (ApVer, Core.Slot, Metadata)
-  , Map UpId (ProtVer, PParams)
-  , Map UpId (ApName, ApVer, Metadata)
-  , Map UpId Core.Slot
-  , Set (UpId, Core.VKeyGenesis)
-  , Set (ProtVer, Core.VKeyGenesis)
-  , Map UpId Core.Slot
+  ( (ProtVer, PParams) -- (pv, pps)
```
Comment (ruhatch) [inline byron/ledger/executable-spec/src/Ledger/Update.hs]: I smell a record ;)

Comment (mhuesch) [reply byron/ledger/executable-spec/src/Ledger/Update.hs]: But this was the 9-tuple I had to write Goblin instances for! We can't let all that somewhat-generic code go to waste! 😝

Comment (dnadales) [reply byron/ledger/executable-spec/src/Ledger/Update.hs]: Hehe, yeah, records are coming :snowflake:

File: byron/ledger/executable-spec/src/Ledger/Core.hs (hunk 2 above)
Comment (dnadales) [reply byron/ledger/executable-spec/src/Ledger/Core.hs]: Hmm, I don't. I'd say having a more liberal instance for `[(a, b)]` is fine here, but maybe because I haven't thought about the properties long enough ;) Do you see a potential problem with this instance?

Comment (uroboros) [reply byron/ledger/executable-spec/src/Ledger/Core.hs]: the Relation property tests we have now don't cover Union override, so it won't cause a problem yet. (Once we test union override, this implementation will probably fail some properties we'd consider reasonable, but not a problem now). 

One thing to do now though is to hook your new relation instance into the Relation property tests (`Ledger.Relation.Properties`)
