### PR TITLE
[1352] Re-enable generation of multiple certs + improve Classifier

### LINKED ISSUE #1352: Generate multiple certificates per transaction
The following properties fail when producing multiple certificates per transaction (determined by `maxCertsPerTx`, temporarily set to 1 again):

* rewardZeroAfterRegKey
* credentialRemovedAfterDereg
* credentialMappingAfterDelegation
* rewardZeroAfterRegPool
* poolIsMarkedForRetirement
* poolRetireInEpoch
* nonNegativeDeposits
* removedAfterPoolreap
* prop_MIRentriesEndUpInMap
* prop_MIRValuesEndUpInMap

### PR DESCRIPTION
**Pull request by uroboros**
Closes #1352 

To enable the generation of multiple certificates per Tx, some further work was required:

**Tx Generation tweaks** 

In `genTx` - when we generate Certificates, we now use the adjusted DPState in subsequent generation (e.g. of Updates in a Tx)

**Changing how we test lower level STS properties based on the higher level ones**

When testing properties based on say DELEG traces, we generate LEDGER traces and "project the traces down" to DELEG level in the form of `[(Source DELEG State, Cert, Target DELEG State)]`. 

Adding multiple certs to aTx caused some DELEG properties to fail because the `TargetState`  referred to by the property was the LEDGER target state, which reflects the state changes that result from an _entire_ transaction, rather than just the changes due to the particular certificate in the transaction.

The fix was to "project a trace down" in a more granular way:

* extracting the Signals from the high level trace (Tx signals in a LEDGER trace, say)
* flattening the certs in those Txs into a list of certificates
* use the Certificates to construct a DELEG (say) trace, which then gives us `[(Source DELEG State, Cert, Target DELEG State)]` with the TargetState only reflecting the particular Cert and not the Tx that the cert is part of

**Fix the Trace Classifier**

The classifier was incorrectly doing `checkCoverage $ conjoin $ <multiple cover statements>`, this is now inverted to `conjoin $ <multiple checkCoverage-cover statements>`.
This change has the effect that far fewer tests are run by QC during trace classification.

### CODE REVIEW

File: shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Generator/Constants.hs [hunk 1]
```diff
@@ -137,7 +137,7 @@ defaultConstants = Constants
   , frequencyTxUpdates = 10
   , minGenesisUTxOouts = 10
   , maxGenesisUTxOouts = 100
-  , maxCertsPerTx = 1
+  , maxCertsPerTx = 3
```
Comment (JaredCorduan) [inline shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Generator/Constants.hs:140]: :tada:
