### PR TITLE
Fix delegation validation

### LINKED ISSUE #3802: Inconsistency on delegation certificates
It seems there is an inconsistency in how delegation certificates are handled. While for normal `ConwayDelegCert` the target pool has to be registered, with `ConwayRegDelegCert` a delegation to an unregistered pool is allowed. This has caused issues to clients, like db-sync https://github.com/input-output-hk/cardano-db-sync/issues/1540 on sanchonet.

 I think the issue comes from using [validateDelegationRegistered](https://github.com/input-output-hk/cardano-ledger/blob/72c1dd752a1761869e8f4b37aafa59858c191bd1/eras/shelley/impl/src/Cardano/Ledger/Shelley/Rules/Delegs.hs#L240) which should be extended for Conway.

### PR DESCRIPTION
**Pull request by lehins**
# Description

Fixes #3802 

Problem was in the fact that we added new certificate type that allows for delegation and registration at the same time, which did not participate in validation of StakePool existence. 

# Checklist

- [x] Commit sequence broadly makes sense and commits have useful messages
- [ ] New tests are added if needed and existing tests are updated
- [x] When applicable, versions are updated in `.cabal` and `CHANGELOG.md` files according to the
      [versioning process](https://github.com/input-output-hk/cardano-ledger/blob/master/RELEASING.md#versioning-process).
- [x] The version bounds in `.cabal` files for all affected packages are updated. **If you change the bounds in a cabal file, that package itself must have a version increase.** (See [RELEASING.md](https://github.com/input-output-hk/cardano-ledger/blob/master/RELEASING.md#versioning-process))
- [x] All visible changes are prepended to the latest section of a `CHANGELOG.md` for the affected packages. **New section is never added with the code changes.** (See [RELEASING.md](https://github.com/input-output-hk/cardano-ledger/blob/master/RELEASING.md#changelogmd))
- [x] Code is formatted with [`fourmolu`](https://github.com/fourmolu/fourmolu) (use `scripts/fourmolize.sh`)
- [x] Cabal files are formatted (use `scripts/cabal-format.sh`)
- [x] [`hie.yaml`](https://github.com/input-output-hk/cardano-ledger/blob/master/hie.yaml) has been updated (use `scripts/gen-hie.sh`)
- [x] Self-reviewed the diff

### CODE REVIEW

File: eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Deleg.hs [hunk 1]
```diff
@@ -68,7 +68,6 @@ data ConwayDelegPredFailure era
   | StakeKeyNotRegisteredDELEG !(Credential 'Staking (EraCrypto era))
   | StakeKeyHasNonZeroRewardAccountBalanceDELEG !Coin
   | DRepAlreadyRegisteredForStakeKeyDELEG !(Credential 'Staking (EraCrypto era))
-  | WrongCertificateTypeDELEG
```
Comment (teodanciu) [inline eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Deleg.hs:71]: Just to make sure I understand: is it the case that the way we validate makes it impossible for this Predicate failure to occur? (But it's still possible in Shelley, since we kept it there, right?)

**Review by teodanciu — APPROVED** [review]
Looks good to me, just a question for my own education.

File: eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Deleg.hs (hunk 1 above)
Comment (lehins) [reply eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Deleg.hs:71]: That is correct. We structured the code in Conway in a smarter way that no longer requires this case. In Shelley it is also an impossible case, so we could do the same for shelley, but that'll be some time later in the future.

File: eras/shelley/impl/src/Cardano/Ledger/Shelley/Rules/Delegs.hs [hunk 2]
```diff
@@ -231,27 +232,27 @@ delegsTransition = do
...
+validateStakePoolDelegateeRegistered ::
+  PState era ->
+  KeyHash 'StakePool (EraCrypto era) ->
   Test (KeyHash 'StakePool (EraCrypto era))
-validateDelegationRegistered certState = \case
-  DelegStakeTxCert _ targetPool ->
-    let stPools = psStakePoolParams $ certPState certState
-     in failureUnless (eval (targetPool ∈ dom stPools)) targetPool
-  _ -> pure ()
+validateStakePoolDelegateeRegistered certState targetPool =
```
Comment (aniketd) [inline eras/shelley/impl/src/Cardano/Ledger/Shelley/Rules/Delegs.hs]:
```suggestion
validateStakePoolDelegateeRegistered poolState targetPool =
```

**Review by aniketd — APPROVED** [review]
Awesome! Thanks! :raised_hands:

File: eras/shelley/impl/src/Cardano/Ledger/Shelley/Rules/Delegs.hs (hunk 2 above)
Comment (lehins) [reply eras/shelley/impl/src/Cardano/Ledger/Shelley/Rules/Delegs.hs]: Thanks. Done
