### PR TITLE
Fix DecCBOR instances to reject `ProtVer` values exceeding the era maximum

### LINKED ISSUE #5631: Failure in Conway CDDL tests
The following test fails:
```bash
cabal test cardano-ledger-conway --test-options='--match "/Conway era-specific/CDDL/Huddle/Decoding fails when term is zapped/proposal_procedure: ProposalProcedure ConwayEra/" --seed 574124041'
```
This failure showed up in this [PR](https://github.com/IntersectMBO/cardano-ledger/pull/5620/checks?check_run_id=66963984829), but is also reproducible in `master`

### LINKED ISSUE #5646: cardano-ledger-conway failure on CI with proposal_procedure cbor zap failure
CI found a failure when running cardano-ledger-conway tests:

```
> cabal run cardano-ledger-conway:test:tests -- --match "/Conway era-specific/CDDL/Huddle/Decoding fails when term is zapped/proposal_procedure: ProposalProcedure ConwayEra/" --seed 2076201456

Conway era-specific
  CDDL
    Huddle
      Decoding fails when term is zapped
        proposal_procedure: ProposalProcedure ConwayEra [✘] (188ms)

Failures:

  testlib/Test/Cardano/Ledger/Binary/Cuddle.hs:155:11: 
  1) Conway era-specific, CDDL, Huddle, Decoding fails when term is zapped, proposal_procedure: ProposalProcedure ConwayEra
       Falsified (after 69 tests):
         Generated term:
         
         84  # list(4)
            18 39  # integer(57)
            58 1d e1 de 3c db e8 8d 21 ca ce 31 03 d1 de b4 
            53 64 7f 5a 4f a1 9f c4 58 28 84 bc 50 15 d6  # bytes(29)
            83  # list(3)
               01  # int(1)
               f6  # null
               82  # list(2)
                  0d  # int(13)
                  18 44  # integer(68)
            82  # list(2)
               78 48 f1 88 95 b9 e0 bd bd e8 bf 96 f2 8f 94 a5 
               eb 97 b1 f3 a2 ba a8 f1 a8 9a 89 f0 91 8b 8c e3 
               bc b5 f3 9f 95 b4 f3 90 b2 9c c7 ad f1 90 84 bd 
               f1 88 99 b0 da a6 f0 bb 82 81 e1 ae 88 e9 a4 8b 
               f2 ae a9 89 f1 89 84 b6 db 81  # text("\296313\3965\36822\587045\46577\929448\427657\70348\16181\914804\855196\
493\327997\296560\1702\241793\7048\39179\715337\299318\1729")
               58 20 bf d2 11 c7 b7 a9 89 40 04 3d d1 be 84 31 
               ab ec 23 30 d0 f6 9b 08 8f a0 e2 44 e6 15 b0 23 
               49 79  # bytes(32)
         
         Validation result:
         array
         └ 2 valid elements
           failed to apply required rule:
           └ ref: gov_action
             └ array
               └ ref hard_fork_initiation_action
                 └ grp (fail)
                   └ 2 valid elements
                     failed to apply required rule:
                     └ ref: protocol_version
                       └ array
                         └ failed to apply required rule:
                           └ ref: major_protocol_version
                             └ failed to apply: 
                                 0 .. 12
         
         Decoding succeeded, expected failure
         

  To rerun use: --match "/Conway era-specific/CDDL/Huddle/Decoding fails when term is zapped/proposal_procedure: ProposalProcedure ConwayEra/" --seed 2076201456

Randomized with seed 2076201456

Finished in 0.1895 seconds
1 example, 1 failure
```

### LINKED ISSUE #5707: CDDL round-trip test failure for `AlonzoTx TopTx ConwayEra`
```
cabal test cardano-ledger-conway:test:tests \
  --test-option=--match="/Conway era-specific/CDDL/Huddle/Generate bytestring from CDDL and decode -> encode/transaction: AlonzoTx TopTx ConwayEra/" \
  --test-option=--seed=78157802
```

It showed up in a PR but is also reproducible on `master` @ 10f240c2.

 _Originally posted by @neilmayhew in [#5631](https://github.com/IntersectMBO/cardano-ledger/issues/5631#issuecomment-4193135358)_

### PR DESCRIPTION
**Pull request by f-f**
# Description

fix #5707, fix #5646, fix #5631 

Re-enable some tests that were disabled due to CDDL mismatches:
- the Alonzo and Babbage CDDL used `positive_interval` instead of `nonnegative_interval` when decoding `Price`s, unlike Conway
- the `ProtVer` in `HardForkInitiation` and `PParamsUpdate` could be higher than the maximum for the era. We now prevent that explicitly in the `DecCBOR` instances.

All the reproducers listed in the tickets mentioned above pass with this patch.

# Checklist

- [x] Commits in meaningful sequence and with useful messages.
- [x] Tests added or updated when needed.
- [x] `CHANGELOG.md` files updated for packages with externally visible changes.  
      **NOTE: _New section is never added with the code changes._** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#changelogmd)).
- [x] Versions updated in `.cabal` and `CHANGELOG.md` files when necessary, according to the
      [versioning process](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process).
- [x] Version bounds in `.cabal` files updated when necessary.  
      **NOTE: _If bounds change in a cabal file, that package itself must have a version increase._** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process)).
- [x] Code formatted (use `scripts/fourmolize.sh`).
- [x] Cabal files formatted (use `scripts/cabal-format.sh`).
- [x] CDDL files are up to date (use `scripts/gen-cddl.sh`)
- [x] [`hie.yaml`](https://github.com/intersectmbo/cardano-ledger/blob/master/hie.yaml) updated (use `scripts/gen-hie.sh`).
- [x] Self-reviewed the diff.

### CODE REVIEW

File: libs/cardano-ledger-core/src/Cardano/Ledger/Core/Era.hs [hunk 1]
```diff
@@ -264,3 +272,17 @@ eraDecoder = toPlainDecoder Nothing (eraProtVerLow @era)
 eraDecoderWithBytes :: forall era t s. Era era => BSL.ByteString -> Decoder s t -> Plain.Decoder s t
 eraDecoderWithBytes bsl = toPlainDecoder (Just bsl) (eraProtVerLow @era)
 {-# INLINE eraDecoderWithBytes #-}
+
+-- | Decoder for `ProtVer` that only accepts versions where the major fits in
+-- the bounds of what's allowed for the provided Era.
+decodeProtVer :: forall era s. Era era => Decoder s ProtVer
```
Comment (lehins) [inline libs/cardano-ledger-core/src/Cardano/Ledger/Core/Era.hs:278]:
```suggestion
--
-- /Note/ - Thanks to the Ledger rules, only the current major protocol version and the very next major protocol version from the current one will be accepted by the Ledger anywhere in the block, regardless that this decoder allows a broader range.
decodeProtVer :: forall era s. Era era => Decoder s ProtVer
```

File: libs/cardano-ledger-core/src/Cardano/Ledger/Core/PParams.hs [hunk 2]
```diff
@@ -259,9 +266,17 @@ instance EraPParams era => DecCBOR (PParamsUpdate era) where
...
         IntMap.fromList
-          [ (fromIntegral ppuTag, field (set ppuLens . SJust) From)
+          [ (fromIntegral ppuTag, mkField ppuLens)
           | PParam {ppUpdate = Just PParamUpdate {ppuTag, ppuLens}} <- eraPParams @era
           ]
+      mkField ::
+        forall t.
+        DecCBOR t =>
+        Lens' (PParamsUpdate era) (StrictMaybe t) -> Field (PParamsUpdate era)
+      mkField ppuLens = case eqT @t @ProtVer of
```
Comment (lehins) [inline libs/cardano-ledger-core/src/Cardano/Ledger/Core/PParams.hs:276]: I am not sure how I feel about this special casing using type level check.
It's cute, but I don't like special cases. 
I am thinking it will be better to add a custom decoder to the `PParam` instead.

```haskell
data PParam era where
  PParam ::
    (DecCBOR t, EncCBOR t, FromJSON t, ToJSON t, ToPlutusData t) =>
    { ppName :: Text
    -- ^ Used as JSON key
    , ppLens :: Lens' (PParams era) t
    , ppEraDecoder :: Maybe (Proxy era -> Decoder s t)
    -- ^ This decoder will be used instead of `decCBOR`, which is helpful when decoder needs access to the `era` parameter, like `ProtVer` for example.
    , ppUpdate :: Maybe (PParamUpdate era t)
    -- ^ Not all protocol parameters have an update functionality in all eras
    } ->
    PParam era
```
Then we'll just need to set `ppEraDecoder = Nothing` for all `PParam`s.

This is a little bit more work, but a bit safer, IMHO.

One example I can think of is if in a future era we will make `PParams` available on chain in some form, then the above special case will break, while this approach will continue to work. Also this will give us a mechanism to apply for other PParams, if we ever need to. Another potential benefit is we will not need to incur unnecessary overhead of type level equality when decoding every PParam.

Please make sure you do adjust `DecCBOR (PParams era)` to use that custom decoder as well.

File: libs/cardano-ledger-core/CHANGELOG.md [hunk 3]
```diff
@@ -1,12 +1,12 @@
 # Version history for `cardano-ledger-core`
 
-## 1.21.0.0
+## 1.20.1.0
```
Comment (lehins) [inline libs/cardano-ledger-core/CHANGELOG.md:3]: Version is invalid, please rebase on `master`  this has been fixed. With master changes there is no need to do a bump

File: libs/cardano-ledger-binary/src/Cardano/Ledger/Binary/Decoding/DecCBOR.hs [hunk 4]
```diff
@@ -207,6 +211,17 @@ instance DecCBOR IPv6 where
   decCBOR = decodeIPv6
   {-# INLINE decCBOR #-}
 
+decodeBoundedRational :: forall a s. (DecCBOR a, Integral a) => Decoder s Rational
+decodeBoundedRational = do
```
Comment (lehins) [inline libs/cardano-ledger-binary/src/Cardano/Ledger/Binary/Decoding/DecCBOR.hs:215]: We probably should call it `Integral`, since there is nothing `Bounded` about it 😅 
```suggestion
decodeIntegralRational :: forall a s. (DecCBOR a, Integral a) => Decoder s Rational
decodeIntegralRational = do
```

File: libs/cardano-ledger-binary/src/Cardano/Ledger/Binary/Decoding/DecCBOR.hs [hunk 5]
```diff
@@ -207,6 +211,17 @@ instance DecCBOR IPv6 where
...
+  assertTag 30
+  values <- decodeList (decCBOR @a)
+  case values of
+    [n, d] -> do
+      when (d == 0) $ fail "Denominator cannot be zero"
+      pure $! toInteger n % toInteger d
+    xs ->
+      cborError $ DecoderErrorSizeMismatch "BoundedRatio" 2 (length xs)
```
Comment (lehins) [inline libs/cardano-ledger-binary/src/Cardano/Ledger/Binary/Decoding/DecCBOR.hs:223]: This decoder is all about a `Rational`
```suggestion
      cborError $ DecoderErrorSizeMismatch "Rational" 2 (length xs)
```

**Review by lehins — CHANGES_REQUESTED** [review]
This is looking great!

File: libs/cardano-ledger-core/src/Cardano/Ledger/Core/Era.hs [hunk 6]
```diff
@@ -264,3 +272,17 @@ eraDecoder = toPlainDecoder Nothing (eraProtVerLow @era)
...
+decodeProtVer = do
```
Comment (teodanciu) [inline libs/cardano-ledger-core/src/Cardano/Ledger/Core/Era.hs]: Wonder if we should call it something more descriptive  - to make it clear it's not the "normal" one used in DecCBOR - perhaps `decodeEraBoundedProtVer` ? 

How come we

File: libs/cardano-ledger-binary/src/Cardano/Ledger/Binary/Decoding/DecCBOR.hs [hunk 7]
```diff
@@ -207,6 +211,17 @@ instance DecCBOR IPv6 where
   decCBOR = decodeIPv6
   {-# INLINE decCBOR #-}
 
+decodeBoundedRational :: forall a s. (DecCBOR a, Integral a) => Decoder s Rational
```
Comment (teodanciu) [inline libs/cardano-ledger-binary/src/Cardano/Ledger/Binary/Decoding/DecCBOR.hs]: Sorry, I'm confused - Is this related to the protocol version change?  Probably not, but just to make sure I'm not missing some implicit connection

File: eras/conway/impl/src/Cardano/Ledger/Conway/Governance/Procedures.hs [hunk 8]
```diff
@@ -860,7 +860,10 @@ instance EraPParams era => DecCBOR (GovAction era) where
           <! D (decodeNullStrictMaybe decCBOR)
           <! From
           <! D (decodeNullStrictMaybe decCBOR)
-      1 -> SumD HardForkInitiation <! D (decodeNullStrictMaybe decCBOR) <! From
+      1 ->
+        SumD HardForkInitiation
+          <! D (decodeNullStrictMaybe decCBOR)
+          <! D (decodeProtVer @era)
```
Comment (teodanciu) [inline eras/conway/impl/src/Cardano/Ledger/Conway/Governance/Procedures.hs:866]: We don't need to start doing this with certain protocol version only?  Because it's impossible to have on chain this atm, right?

**Review by teodanciu — COMMENTED** [review]
A few questions from me!

File: libs/cardano-ledger-binary/src/Cardano/Ledger/Binary/Decoding/DecCBOR.hs (hunk 7 above)
Comment (f-f) [reply libs/cardano-ledger-binary/src/Cardano/Ledger/Binary/Decoding/DecCBOR.hs:214]: Sorry this got a bit sprawly as I tried to get to the bottom of the failures 😄 
This is not related to the protocol version change, but related to the CDDL adjustments for Alonzo and Babbage (`positive_interval` -> `nonnegative_interval`) that are also needed for these flaky tests to pass

File: libs/cardano-ledger-binary/src/Cardano/Ledger/Binary/Decoding/DecCBOR.hs (hunk 5 above)
Comment (f-f) [reply libs/cardano-ledger-binary/src/Cardano/Ledger/Binary/Decoding/DecCBOR.hs:223]: ah yes thanks for the catch, this is a leftover from the previous iteration

File: libs/cardano-ledger-core/src/Cardano/Ledger/Core/PParams.hs (hunk 2 above)
Comment (f-f) [reply libs/cardano-ledger-core/src/Cardano/Ledger/Core/PParams.hs]: Right, this makes sense - I considered adding the additional field but went with this typelevel equality as it was more lightweight. But the benefits you list for these make sense so I will rework this to apply your suggestion

File: eras/conway/impl/src/Cardano/Ledger/Conway/Governance/Procedures.hs (hunk 8 above)
Comment (f-f) [reply eras/conway/impl/src/Cardano/Ledger/Conway/Governance/Procedures.hs:866]: Yes, this is alright because the rules are already stricter than this, see [this comment](https://github.com/IntersectMBO/cardano-ledger/pull/5736/changes#r3102480808)

Comment (lehins) [reply eras/conway/impl/src/Cardano/Ledger/Conway/Governance/Procedures.hs:866]: So yeah, we do need to start doing this for conformance with CDDL. And the only reason why we can do this is because what @f-f said above

File: libs/cardano-ledger-binary/src/Cardano/Ledger/Binary/Decoding/DecCBOR.hs (hunk 4 above)
Comment (lehins) [reply libs/cardano-ledger-binary/src/Cardano/Ledger/Binary/Decoding/DecCBOR.hs]: Looks like you missed this one

File: libs/cardano-ledger-binary/src/Cardano/Ledger/Binary/Decoding/DecCBOR.hs (hunk 5 above)
Comment (lehins) [reply libs/cardano-ledger-binary/src/Cardano/Ledger/Binary/Decoding/DecCBOR.hs]: And this one 😄

Comment (f-f) [reply libs/cardano-ledger-binary/src/Cardano/Ledger/Binary/Decoding/DecCBOR.hs:223]: I just rebased, still sorting out the rest

File: libs/cardano-ledger-core/src/Cardano/Ledger/Core/Era.hs (hunk 1 above)
Comment (lehins) [reply libs/cardano-ledger-core/src/Cardano/Ledger/Core/Era.hs]: One more thing about this decoder. Let's put it next to the type `ProtVer` in `BaseTypes` module. I don't think `Core.Era` is the right module for it

File: libs/cardano-ledger-core/src/Cardano/Ledger/Core/Era.hs (hunk 6 above)
Comment (lehins) [reply libs/cardano-ledger-core/src/Cardano/Ledger/Core/Era.hs]: This is a very interesting observation, but in the opposite direction. We should be using this decoder as the default one!
The only place where we cannot use this decoder is in `PParams` (not in the `PParamsUpdate`).

However, the problem is that in the regular `DecCBOR` interface we are lacking access to `era` parameter. 

Maybe we should add a couple of type class like this?
```haskell
class EncEraCBOR a where
  encEraCBOR :: Proxy era -> a -> Encoding

class DecEraCBOR a where
  decEraCBOR :: Proxy era -> Decoder s a
```

We definitely do not want to do this in this PR, this is more of an idea.
However, that being said, this name is fine IMHO, bit it does need some haddock describing how is it different from `decCBOR` for `ProtVer` and why

File: libs/cardano-ledger-core/src/Cardano/Ledger/Core/PParams.hs (hunk 2 above)
Comment (lehins) [reply libs/cardano-ledger-core/src/Cardano/Ledger/Core/PParams.hs]: > Please make sure you do adjust DecCBOR (PParams era) to use that custom decoder as well.

I just realized that this decoder will not be correct for `PParams` as it is today, cause there can be a case when PV in PParams is one lower than the current era `protVerLow`, because of this field that we have in the ledger state called `prevPParamsGovStateL`, which holds PParams from previous epoch, thus can hold PParams from previous era!
This thought process made me realize that our representation of the `prevPParamsGovStateL` field is wrong 🤦 

So, don't change the decoder for `PParams` in this PR, but create a ticket about adjusting it in the future. Because once we fix this issue of representation of PParams for `prevPParamsGovStateL`, we should switch the decoder for PParams as well.

Comment (lehins) [reply libs/cardano-ledger-core/src/Cardano/Ledger/Core/PParams.hs]: FTR. https://github.com/IntersectMBO/cardano-ledger/issues/5759

File: libs/cardano-ledger-core/src/Cardano/Ledger/Core/Era.hs [hunk 9]
```diff
@@ -51,8 +51,10 @@ module Cardano.Ledger.Core.Era (
   fromEraShareCBOR,
   eraDecoder,
   eraDecoderWithBytes,
+  decodeProtVer,
```
Comment (lehins) [inline libs/cardano-ledger-core/src/Cardano/Ledger/Core/Era.hs]: It doesn't look like you need it here
```suggestion
```

File: libs/cardano-ledger-core/src/Cardano/Ledger/Core/Era.hs [hunk 10]
```diff
@@ -51,8 +51,10 @@ module Cardano.Ledger.Core.Era (
...
 ) where
 
+import Cardano.Ledger.BaseTypes (decodeProtVer)
```
Comment (lehins) [inline libs/cardano-ledger-core/src/Cardano/Ledger/Core/Era.hs]:
```suggestion
```

File: libs/cardano-ledger-core/src/Cardano/Ledger/BaseTypes.hs [hunk 11]
```diff
@@ -131,6 +137,7 @@ import Cardano.Ledger.Binary.Plain (
 import qualified Cardano.Ledger.Binary.Plain as Plain
 import Cardano.Ledger.Binary.Version
 import Cardano.Ledger.Hashes (HashAnnotated, SafeHash, SafeToHash)
+import Cardano.Ledger.Internal.Era (Era (..))
```
Comment (lehins) [inline libs/cardano-ledger-core/src/Cardano/Ledger/BaseTypes.hs]: My other comment resolved circular dependency, so no need to reach out for rinternal
```suggestion
import Cardano.Ledger.Core.Era (Era (..))
```

File: libs/cardano-ledger-core/src/Cardano/Ledger/BaseTypes.hs [hunk 12]
```diff
@@ -21,11 +22,15 @@
 {-# LANGUAGE TypeFamilies #-}
 {-# LANGUAGE UndecidableInstances #-}
 {-# LANGUAGE ViewPatterns #-}
+#if __GLASGOW_HASKELL__ >= 908
+{-# OPTIONS_GHC -Wno-x-unsafe-ledger-internal #-}
+#endif
```
Comment (lehins) [inline libs/cardano-ledger-core/src/Cardano/Ledger/BaseTypes.hs]: Ditto
```suggestion
```

**Review by lehins — APPROVED** [review]
Beautiful.
The only suggestion I have is to avoid using `Internal`, since it doesn't look like it is necessary

**Comment by f-f** [comment]
@lehins thanks for catching this! Should be all good now
