### PR TITLE
fix pool cent refund accounting

### LINKED ISSUE #845: Stake pool certificate refunds deducted from the deposit pot
The stake pool certificate refunds are *not* currently being properly accounted for in the deposit pot when the pool is reaped.

### PR DESCRIPTION
**Pull request by JaredCorduan**
There were a couple of problems with the pool certificate refunds in the `POOLREAP` transition.

First, the sum total of the (claimed and unclaimed) refunds that was handed out was not deducted from the global deposit pot. In fact, the `UTxOState` wasn't even in scope. Therefore I added the `UTxOState` to the `POOLREAP` state in both the formal spec and the exec model, and the appropriate amount is removed from the deposit pot.

Second, the slot duration given to the refund calculation was incorrect.  For the current epoch `e`, it was calculating `firstSlot e - firstSlot e` for every duration. In other words, the full refund was always being handed back. The fix was to get the slot when the pools were registered from `stpools`.

I added new tests. For each example in `test/Example` there is now a new test that the expected state contains exactly forty-five billion ada. This did mean changing the numbers in the test a little bit, since, for instance, we did not always start off with forty-five billion ada in all the examples. which in turn does effect the reward calculations, etc.

closes #845

### CODE REVIEW

File: shelley/chain-and-ledger/executable-spec/test/Examples.hs [hunk 1]
```diff
@@ -434,16 +441,18 @@ utxostEx2A = UTxOState utxoEx2A (Coin 0) (Coin 0) usEx2A
 lsEx2A :: LedgerState
 lsEx2A = LedgerState utxostEx2A (DPState dsEx1 psEx1) 0
 
+fortyFiveBillionAda :: Coin
+fortyFiveBillionAda = Coin 45*1000*1000*1000*1000*1000
```
Comment (mgudemann) [inline shelley/chain-and-ledger/executable-spec/test/Examples.hs]: maybe `maxAdaSupply` oder `maxLovelaceSupply` ?

File: shelley/chain-and-ledger/formal-spec/epoch.tex [hunk 2]
```diff
@@ -548,6 +556,13 @@ \subsection{Pool Reaping Transition}
       \trans{poolreap}{e}
       \left(
         \begin{array}{rcl}
+          \var{utxo} \\
+          \varUpdate{\var{deposits}}
+          & \varUpdate{-}
+          & \varUpdate{(\var{unclaimed} + \var{refunded})} \\
```
Comment (mgudemann) [inline shelley/chain-and-ledger/formal-spec/epoch.tex]: I suppose this cannot be negative in total? Maybe add a not on that property.

Comment (JaredCorduan) [reply shelley/chain-and-ledger/formal-spec/epoch.tex]: yes, that's the property, I'll add it to the list I've got going!
